### ISSUE TITLE
HUC6 spatial aggregation

### ISSUE THREAD

**Issue by sfoks** [hytest-org/hytest#10]
I wasn't sure if I should put this issue under [this issue ](https://github.com/hytest-org/hytest/issues/3).

For the HUC12 spatial aggregations, there are many versions of this. The last version will be sometime in the next two years. 

Currently, the hyriver - [pynhd](https://github.com/hyriver/pynhd) repo uses the latest/newest edits on the WBD HUC12. 

But we may want to use the [Mainstems](https://www.sciencebase.gov/catalog/item/60cb5edfd34e86b938a373f4) version of HUC12 due to the national water assessment's use of the same version (to keep cohesion).

**Comment by thodson-usgs** [comment]
If we're thoughtful, it should be easy to swap down the line.

My suggestion is to:
- create the initial workflow with pynhd (if that's not performant, move the data to s3)
- link this or another issue to the workflow notebook, so that we can revisit this later
- at any point, put the Mainstems version on S3, incorporate into the old workflow, and reprocess.

**Comment by thodson-usgs** [comment]
I'm finding lots of holes in the basin polygons from NHD.
Here's how I remove them, though it assumes the main basin polygon is at index 0 of geoms:
```python
basins = basins.geometry.apply(lambda a: Polygon(a.geoms[0].exterior) if a.geom_type == 'MultiPolygon' else Polygon(a.exterior))
```

**Comment by sfoks** [comment]
This is NHDPlusV2 right? We should be consistent with the version of the snapshot because of these holes or where the HUC12s don't perfectly align. This is really Dave Blodgett's and Andy Bock's world. We should ask them the best solution perhaps.

**Comment by rsignell-usgs** [comment]
@alaws-USGS , here is the Pangeo Discourse post by Ryan talking about conservative aggregation using geopandas, xarray and dask: https://discourse.pangeo.io/t/conservative-region-aggregation-with-xarray-geopandas-and-sparse/2715
