### ISSUE TITLE
CONUS404 on AWS Open Data Program

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#104]
On October 5, I received this email from Chris Stoner at AWS: 

> Congratulations! We have reviewed your application and are happy to confirm that CONUS404 is eligible for the AWS Open Data Sponsorship Program. For next steps, please refer to the Onboarding Handbook for Data Providers, available at https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf. 

The steps in the PDF are:

1. APPLY - Submit applications via online web form. We typically process applications and communicate results via email within two weeks of your submission.
2. PREPARE DOCUMENTATION - Program participants must provide documentation and an
example tutorial of working with their dataset on AWS. Development of these resources can
happen in tandem with other steps, but must be completed prior to dataset launch.
3. SIGN TERMS & CONDITIONS - Agree to the program’s legal agreement via the online web
form.
4. CREATE & LINK NEW AWS ACCOUNT - Create a pristine AWS account that will be used
exclusively for hosting your dataset.
This account must then be linked to the program’s billing organization1 prior to the account’s
use. You will provide your new AWS account number to opendata@amazon, and we will issue
an invitation to link your account. Important: You are responsible for any charges incurred
prior to confirmed account linking.
5. PREPARE AND UPLOAD DATA - Upload and organize your data into a newly created Amazon
S3 bucket created using a supplied Cloud Formation template.
6. LIST DATASET ON THE REGISTRY OF OPEN DATA & LAUNCH! - Submit your dataset’s
registry listing entry as a .yaml file via Github. The AWS Open Data team will review and
merge your pull request. This must be in place before quarterly launch announcement.

**Comment by rsignell-usgs** [comment]
Step 1 is obviously complete.  

Step 3 will shortly be complete, as Megan Frayer,  Compliance Branch Chief in the WMA Enterprise Technology Office, will be signing the AWS Open Data Terms and Conditions.   We received approval previously from Sheryl Rakestraw, Senior Attorney for DOI, that there were no legal issues with this.

**Comment by rviger-usgs** [comment]
Thinking Step 2 will be met by the USGS Web Page that's the formal "web release" for the dataset. This page should go live pretty much in sync with the appearance of the data on ODS. 

There's also the journal article, but I expect that to be released a month or two after the appearance of the data on ODS (so might want to drop that from dialog w/Amazon, if we think that'll clutter the discussion).

**Comment by rviger-usgs** [comment]
For Step 3, we're shopping the "who should sign?" question with ACIO now (Carter Elmore, WMA ETO Director elevated it). Part of it is influenced by whether we can/want to have this done for the whole bureau in one shot or we just want to go for it at the WMA level to get it done quick.

Rich is working on Step 4, which is related, to bring together the Amazon Fed Rep, the Amazon ODS rep, and the CHS Amazon contract boss to talk w/us.  Right now, we're trying to determine whether we're even able to make a "fresh account" and how that relates to USGS' existing account(s).

**Comment by amsnyder** [comment]
**DOCUMENTATION**
Hi both - just looking into the documentation piece of the AWS Open Data Sponsorship in more detail. I think we need 3 things:
1. a link to a web page with documentation describing data organization (hosted by us, like [this](https://github.com/teamookla/ookla-open-data))
2. example notebooks of how to use the data
3. we need to fill out the [Amazon Open Data Registry template](https://github.com/awslabs/open-data-registry/) for the documentation that shows up on their page

For **#1** my gut instinct was to use the drupal web page - I can talk to Krista about making a section of the web page specifically about the Open Data Sponsorship data. A concern with that could be timeline though - not sure if the web page will be up in time. Another option is to make a markdown file in our Github for this. Just wanted to see if y'all thought this is legitimate enough (we don't need to go through some kind of approval process for this type of content, right? - especially if NCAR is now signing?). I'd like to ask if we can update this documentation link (maybe we start with a github markdown file then transition to the web page later). I'll take a stab at drafting this text, but I won't be able to fill in the details until we decide exactly what subset of the data we are sending to them. Two questions here for @rviger-usgs and @rsignell-usgs:
- What do y'all think about using the github markdown until our drupal page is up?
- Can I reach out to ask if we can update this url (maybe once we get the signature piece figured out)


For **#2** Rich and I discussed some notebooks to explore and export netcdfs of CONUS404. I will make sure they are ready to go.

For **#3** I can fill out this template. I don't believe I should push it anywhere yet, but I'll have it filled out so it's ready to go when we need it.

**Comment by rviger-usgs** [comment]
@amsnyder This all sounds great. 

I'm okay w/your plan of going with a github page to start, eventually shifting to a drupal (or ScienceBase) page eventually, if we need to. Think we should check in w/Krista and the WMA Drupal folks (need to figure out the real name of this team!) about the timeline there, in case that's actually quick enough.  Checking w/Amazon on whether we can change that would also be good.  

Do we want to loop an NCAR person into this issue re: this whole process and signing the paperwork? I can try to identify who that ought to be, if we're ready for that.

**Comment by rsignell-usgs** [comment]
@rviger-usgs I think we need to abandon the idea of USGS being the maintainer of an AWS Public Data Set, at least for now.   Although the DOI lawyers were okay with the [AWS Open Data Sponsorship Program Terms and Conditions](https://aws.amazon.com/opendata/open-data-sponsorship-program/terms/), USGS apparently cannot set up a totally new AWS account that the program demands for linking with the AWS corporate account.   

However, we don't have to abandon the idea of the CONUS404 data being available on AWS Public Data.  Once USGS publishes data, anyone 3rd party is free to be the maintainer of that data on the AWS Open Data Program.   This is what Planet.os did with USGS Landsat data before USGS had it available in cloud storage.   

If another organization, say NCAR, would find value in the data being there, they could be the maintainer.   USGS doesn't have a role in this, so we don't need to wait to hear from senior USGS management.

**Comment by rviger-usgs** [comment]
@rsignell-usgs okay, I think we should do as you recommend. Let's close this issue and focus on the globus/black pearl solution.
