### ISSUE TITLE
CONUS404 GLOBUS-Black Pearl data release

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#105]
Hi all - starting a thread to discuss Black Pearl - GLOBUS endpoint.

@rviger-usgs are you on board with doing a formal data release on ScienceBase if Jeff Falgout gives us the green light?

I believe that means our DOI for CONUS404 would now be pointing to the ScienceBase page (not the Drupal page), right? We will need to update that information in a few places, I imagine.

FYI: @kadunne-usgs @rsignell-usgs @alamotte-usgs

**Comment by rviger-usgs** [comment]
Hi Amelia, 

I guess I'd like to make sure no one has an objection based on cost or anything before going from web release to data release. If not, I'm all for it. 

The planned page is not intended to directly serve the data content itself, it is a way to aggregate more than one way to pull the content but keep literature citations pointing at a single DOI (regardless of which endpoint a user opted to use). If we can ensure the ScienceBase page can do the same, then yes let's point the DOI at the ScienceBase page. Would be great if we can use the text for the planned drupal page in Sciencebase. 

I'm okay with exploring using a ScienceBase/Globus/Black Pearl endpoint as a public distribution channel.

**Comment by rsignell-usgs** [comment]
I'm excited about having an endpoint from which people (including us) can actually retrieve the data!   We still anticipate folks will mostly be using our "non-authoritative" access points instead of the globus link to the tape archive, but this seems like a much better path than a web release workaround.

**Comment by amsnyder** [comment]
@rviger-usgs - Is there anyone we should check with on the cost or other potential objections besides ScienceBase, Dave, and Jeff Falgout?

**Comment by rviger-usgs** [comment]
@amsnyder Those three are good. Once we have the technical consensus and any policy thoughts, I'll want to take this to WMA management, if only to let them know of any shift in the plan around the release of CONUS404.

**Comment by amsnyder** [comment]
I think I've located most/all of the data on Black Pearl and tracked it in our [CONUS404 versions list](https://doimspp.sharepoint.com/:x:/r/sites/gs-wma-hytest/_layouts/15/Doc.aspx?sourcedoc=%7BD2A499D7-027E-42E5-B0BA-13BA48B32569%7D&file=CONUS404%20versions.xlsx&action=default&mobileredirect=true&CID=A408B70C-6919-4CD8-A73A-02CB1B092245&wdLOR=cD24AE203-57E3-41B5-A1FB-EE0BECCB8766).

I asked Kyoko for her plans of how and when she will push new years of data to Black Pearl - we might need to talk to SB about making updates to our GLOBUS endpoint and having data release revisions as these years become available.

We have invited Jeff Falgout to the HyTest meeting tomorrow to discuss more, but waiting to hear back if he is available.

**Comment by amsnyder** [comment]
After meeting with Jeff, we seem to be in agreement that we will do a data release with a GLOBUS - Black Pearl endpoint.

We need to send Jeff our DOI for the data release. @alamotte-usgs is checking on if we can throw out the DOI he already made so that we can use the DOI that is auto-generated by the ScienceBase data release tool. If we switch to a new DOI, we will need to update (1) the metadata.xml file and (2) send to NCAR for their use in RDA, if it is pursued.

Once we have our final DOI, Jeff will make a GLOBUS endpoint and give me access. I will transfer the wrfout, auxhist24, and wrfxtrm files (see [here](https://doimspp.sharepoint.com/:x:/r/sites/gs-wma-hytest/_layouts/15/Doc.aspx?sourcedoc=%7BD2A499D7-027E-42E5-B0BA-13BA48B32569%7D&file=CONUS404%20versions.xlsx&action=default&mobileredirect=true&CID=A408B70C-6919-4CD8-A73A-02CB1B092245&wdLOR=cD24AE203-57E3-41B5-A1FB-EE0BECCB8766) for details) for all water years into the bucket Jeff has made. @kadunne-usgs - We need to ask Kyoko if we can delete the files from their current locations in `/wrfconus404-disk/` and `/wrfconus404/` once we have transferred them. She will have access to this new public endpoint, but we want to make sure it won't create any issues with her workflows that she is using.

@alamotte-usgs and I will work on creating the IPDS record and ScienceBase page for the data release today or on Monday.

We know that Kyoko will be adding new years of data as they become available and we will want to add them to the data release. Jeff says adding these to the GLOBUS endpoint will be easy. For the ScienceBase page, we will need to go through a level 3 revision process, which is supposed to be pretty straightforward.

We discussed the cost of this long term storage a bit. We don't have any firm numbers, but we think worst case scenario is $10-15k per decade of storage.

@rviger-usgs @alamotte-usgs - did I miss anything here?

**Comment by kadunne-usgs** [comment]
Do you know if we will be able to link to other access pathways (e.g. AODS, RDA) from the ScienceBase page?

**Comment by amsnyder** [comment]
@kadunne-usgs I believe we can updated SB pages to include links of related publications/releases after publishing. Happy to dig into this if @alamotte-usgs doesn't know the answer - but let's see if he has input first.

**Comment by rviger-usgs** [comment]
@kadunne-usgs yes, a Sciencebase page can point to multiple endpoints (the [John Warner example](https://www.sciencebase.gov/catalog/item/610acd4fd34ef8d7056893da) does this, in fact). 

@amsnyder yes, think you've got everything! amazing job. thanks for that. The only thing that we might want to add to that is to have Kyoko or whoever on the NCAR end formally notify us whenever there's a new increment to add to the raw CONUS404 historical dataset.

**Comment by alamotte-usgs** [comment]
@rviger-usgs  We will use the previously reserved DOI: **10.5066/P9PHPK4F** or to be precise: **HTTPS://doi.org/10.5066/P9PHPK4F** and the metadata will need to be updated. One thing to consider is the messaging with the data release. It should be painfully clear that the GLOBUS endpoint is probably not the preferred data that a modeler is looking for and has a large download time investment. [or something like that]

**Comment by rviger-usgs** [comment]
@alamotte-usgs understand re: preferred channel. I'm guessing we'd add that language after the initial release (since there won't be another channel until after the initial release). Same applies to adding additional variables to the cloud version (which won't exist initially). Could definitely include warning about usability of the default download channel. I asked Jeff F re: performance; he'll be getting back to us (week after next would be the earliest).
