### ISSUE TITLE
What is a release

### ISSUE THREAD

**Issue by gzt5142** [hytest-org/hytest#107]
Related to #73 and #56 ...

A gitub action is now installed on this repo.  It fires with every merge into the `main` branch. That could be a merge from `dev` or a feature branch.  I believe it will also fire with commits direct to `main` -- I did not test this, as I understood our workflow is to always work on a separate branch for changes to `main`. 

Upon merge, the action will bundle up the essential components that a user will need to set up their conda environment and start using hytest workflows on their own jupyter server. The quickstart instructions refer to a download of this bundle of essential information as the minimum download to start (as opposed to cloning the repo). 

An archive such as this is an 'asset' associated with a package or release in the github ecosystem. It is associated with a tag, which I made to match semantic versioning standards.  The instructions for how to create a release are included in the `.github/workflows` folder.

**Comment by gzt5142** [comment]
@amsnyder -- do you want this information documented in the repository somewhere?  Perhaps as part of the README? Elsewhere?

**Comment by amsnyder** [comment]
Yes - could you put it in the release description for now? That way when someone clicks on the release, they will see what exactly is contained in the release and what it is used for.

**Comment by gzt5142** [comment]
Done
