### ISSUE TITLE
CONUS404 bias-adjusted 42-year forcing data

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#108]
The CONUS404 bias-adjusted 42-year hourly forcing data from NCAR has been transferred to denali at:
`/caldera/hytest_scratch/scratch/forcing42year/tpBiasCorr`

At this time the only bias-adjusted variables are temperature (`T2D`) and rain (`RAINRATE`).

Next steps will be to create a zarr store for the hourly and then create daily values from this.

**Comment by rviger-usgs** [comment]
I know that bias-adjustment was only applied to precip & temp, but are those the only 2 vars in the data? I know that's all PRMS needs, but are the other variables that the WRF-Hydro application will need in what's been Globus'd to Denali, too? (I know those other variables do not need to go to daily, since PRMS wouldn't consume them).

**Comment by rviger-usgs** [comment]
@pnorton-usgs @rsignell-usgs do we want to add Jacob, Rich McDonald or anyone else to this issue for the workflow on summarizing to daily and HRUs? Also, if it makes sense, do we want to document that workflow so other folks can do this kind of work in future?

**Comment by rsignell-usgs** [comment]
@pnorton-usgs , looks like we already have the bias corrected on our "loaner" OSN space at RENCI:
``` 
(pangeo) [rsignell@tg-dtn1 ~] rclone lsl osn-renc:rsignellbucket2/rmcd/conus404_hourly_biascorrected.zarr/.zmetadata
     8143 2022-10-19 14:56:32.000000000 .zmetadata
```
There haven't been new updates on that dataset, right?

**Comment by rviger-usgs** [comment]
@pnorton-usgs 

1. both of those datasets are expressed on the 1km NWM grid mesh?
2. who is expected to use the hourly T2D and RAINRATE info?

**Comment by pnorton-usgs** [comment]
> @pnorton-usgs
> 
> 1. both of those datasets are expressed on the 1km NWM grid mesh?
> 2. who is expected to use the hourly T2D and RAINRATE info?

@rsignell-usgs 
1. Both dataset using the 1km grid spacing. The domain is slightly smaller than the CONUS404 domain
2. I'm not sure who will want to use the hourly. I needed it to create the daily. We could just opt to keep the hourly on-prem until/unless someone needs it on the cloud.

**Comment by rviger-usgs** [comment]
thanks for that call, Parker. Think cleaning up will be a very important job since we're cranking quite a few variants to different end points. Also encourage us to call out which of these are things we should be publicizing to which groups.

**Comment by rmcd-mscb** [comment]
I think the DRB stream-temperature folks - Jake Zwart etc might be interested in the hourly data.

**Comment by rmcd-mscb** [comment]
@pnorton-usgs I've added the c404bc data processed to gfv1.1 to here: /caldera/projects/usgs/water/wbeep/onhm_dev/climate/c404bc.  I've done it by calendar year following the same patter we have with other datasets, so 1980-2021 by year

**Comment by rviger-usgs** [comment]
If this means IWAA National Applications project is good to go, great! 

Looks like @rmcd-mscb and others are already cranking on https://github.com/hytest-org/hytest/issues/120. Also great! 

Wondering if this issue should be closed? Thinking any discussion about data releases around this, formalizing workflow, or repeating the workflow would be new issues?

**Comment by pnorton-usgs** [comment]
I'm going to close this issue since we've addressed what needed to be done. Any future discussion can be done in a new issue.
