### ISSUE TITLE
dev branch deletion

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#110]
We decided today to remove the 'dev' branch from our workflow. To make changes to our Github we will make a new feature branch, request review, then merge directly into main once it has been approved.

There are likely some differences between `dev` and `main`, and I don't want to merge them in without explicit approval from @gzt5142 and @alaws-USGS. Could one of you open a pull request and make sure it is ready to be merged with main? Then I can review it, merge it, and delete the dev branch.

**Comment by alaws-USGS** [comment]
@amsnyder @gzt5142 Feel free to remove dev, I'm all set.

**Comment by amsnyder** [comment]
I merged in the PR, and set `main` as the default branch. Am I free to delete the `dev` branch? Anything else you can think of that we need to do?

**Comment by alaws-USGS** [comment]
@amsnyder you should be good to delete `dev`

**Comment by amsnyder** [comment]
RIP dev
