### ISSUE TITLE
PUMP ML/RIMBE Data Storage

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#112]
PUMP ML and RIMBE have a coordinated data science team for FY23 that will be doing dataset processing needed for:

- PUMP national machine learning modeling
- RIMBE base evaluation for IWAAs basins

We do not yet have a fully finalized list of the datasets we will be processing, but I'll try to lay out the details I currently know. We anticipate creating a number of cloud-optimized gridded datasets. We also plan to aggregate a number of point and gridded datasets to (1) HRUs and (2) the stream reach network used by the NHM (maybe GFv1 or v2).

The datasets we anticipate the PUMP ML modelers needing that we will process at a national scale are:

- harmonized water quality data from WQP and other sources
- gridMET
- NOAA GEFS
- Land cover attributes from [several sources](https://github.com/USGS-R/drb-inland-salinity-ml/blob/main/1_fetch/in/NHDVarsOfInterest.csv) (including many Wieczorek datasets)
- a river distance matrix showing the distance between various river segments

The datasets that RIMBE knows it will need SO FAR (many more to come) are:

- Livneh climate data
- CMIP5 climate data
- FORE-SCE land cover data

The RIMBE datasets will likely be processed for the DRB, but our workflows will later be used to process data for other IWAAs basins.

We anticipate these datasets being widely useful to many modelers working at IWAAs or national scales, and we want to make them accessible. **Once the Open Storage Network pod is set up, would HyTEST allow us to store all of these datasets in this space?** @rviger-usgs and @rsignell-usgs - I personally think this is a good use of this space, but I want to make sure you are on board with it too.

We plan to expose the location of these datasets through the NHGF catalogs to increase their discoverability as well.

**Comment by amsnyder** [comment]
@lekoenig and @padilla410 are heading up the data science team with me, so tagging them to follow along.

**Comment by rviger-usgs** [comment]
@amsnyder I'm open to using the Storage Pod this way. Think we need to come up with a vision for how we use that asset, as well as the Pavillion flash array we have on Denali (/caldera/hytest_scratch). Could be we stage on a higher-performance asset for initial phase and then move to something cheaper (like Black Pearl) once the rush dies down.

Think we should also be talking with NHGF and possibly others, about additional storage options.
