### ISSUE TITLE
CONUS404 dataset update strategy

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#114]
We need to come up with a strategy for keeping all of our versions of CONUS404 up to date. I understand that the data is being updated for two reasons:
- small corrections are being applied to the existing dataset
- additional years of data are being added

Currently I don't have an understanding of how those updates are being propagated through the various versions of data we have on:
- Black Pearl
- Caldera
- S3
- anywhere else?

We need to come up with a more systematic or automated way to keep all of our copies of CONUS404 up to date, and track the changes that are being made with each update. @pnorton-usgs - could you add any context you have about the current communication and update process?

**Comment by rviger-usgs** [comment]
would like to track what the proposed updates are, even if only to measure/progress on this work. I think the appending of extra years is non-controversial but versioning probably still needs to happen there. The small corrections thing could require a little more nuance.

**Comment by amsnyder** [comment]
We are working on populating a spreadsheet to document the various versions of CONUS404:
https://doimspp.sharepoint.com/:x:/s/gs-wma-hytest/EdeZpNJ-AuVCsLoTukizJWkBIVEkp5wvJF4N0RdOSvqf-A?e=uOFYm4

Once we have all the versions of the dataset compiled, we can discuss as update strategy in a meeting.

**Comment by amsnyder** [comment]
Yes, actually I'll close that issue and consolidate the discussion here. Just bringing over your two notes so we don't lose them:

1. make sure [this Sharepoint page](https://doimspp.sharepoint.com/sites/gs-wma-hytest/SitePages/CONUS404-Initial-Variables.aspx?source=https%3a//doimspp.sharepoint.com/sites/gs-wma-hytest/SitePages/Forms/ByAuthor.aspx) is consistent w/what's available on our internal S3 bucket and what will be shared via Amazon ODS.
2. understand which variables in the list from the PUMP DRB folks and from NCAR are NOT present and figure out a plan for those (even if only to say, "no, those aren't included"). @kadunne-usgs can you add to this one?

**Comment by amsnyder** [comment]
There were 4 main tasks coming out of this call:
#120 Add CONUS404 processing scripts to Github - @pnorton-usgs will work on this soon
#121 Dependency tracking of CONUS404 derivative datasets - @pnorton-usgs will work on this soon
#122 Communicate CONUS404 dataset changes to users - @amsnyder will work on a draft of this method and revisit with @pnorton-usgs and @rsignell-usgs 
#123 Propagate dataset changes through derivative CONUS404 versions - we did not come up with a solution for this, but we will revisit once we make some progress on the above 3 tasks.
