### ISSUE TITLE
IWAA Calibration work compute resources

### ISSUE THREAD

**Issue by arezoorn** [hytest-org/hytest#116]
For the National Water Model we usually calibrate many gauges. In our last effort we calibrated around 1500 basins, and on average using 9 cores per basin. That adds up to roughly around 13500 cores that were used for an extended amount of time (ranging between two weeks to a month and half). The smaller basins will finish sooner and release the resources. 

To my understanding of working for few days on Denali, there is only 232 nodes (9280 core). So the total number of cores available is less than what I usually use on Cheyenne. We probably could reduce the number of cores per model a little, or scale down on the number of basins we want to calibrate for the IWAA. 

I think we want to let users know that there will be such large tasks that will take about a month or 1 month and half and will keep the queue busy. @rviger-usgs asking for dedicate node as you mentioned in other thread seems like a good idea. 

Thanks!

**Comment by rviger-usgs** [comment]
(note this is related to [https://github.com/hytest-org/hytest/issues/109](https://github.com/hytest-org/hytest/issues/109))

**Comment by rsignell-usgs** [comment]
Would this also be a good use case for doing on the Cloud?   This is not HPC work, but embarrassingly parallel work, right @arezoorn ?

**Comment by arezoorn** [comment]
I have zero experience myself on cloud, so it would be good if @ishita9 could comment also.  But here is my attempt to naser. There are two different things. 

1- Pre calibration forcing cutout (which is not parallel, it is embarrassingly parallel). It is all IO. From the work that Mike Fienen and I were doing, and our previous NCAR work on cloud) my impression was that the download/upload is not great. It was taking a long time for Mike to upload one of these basins domain files (after cutout) to cloud. So my impression is that, it would be doable to do on cloud but probably pulling it down from cloud for next step would become an issue). 

2- Calibration workflow: The workflow we has in intended and optimized for running on HPC. We run WRF-Hydro with more than one core usually for these exercise, and share the resources among different basins. Usually running few of these basins on one node but each basin is parallelize (MPI). 

I do not think the time we have for this project allows us to go toward cloud base solutions. My understanding is that there will be a good amount of work that needs to be done to make it work at such a scale. We have done calibration on cloud with our current workflow, however for only a few basins. @ishita9 could comment further since she did all the backend work for the single basin calibration on cloud. 

Thanks!
Arezoo

**Comment by rsignell-usgs** [comment]
@arezoorn, okay, thanks for the detailed response.   Indeed, sounds not a good time to try cloud on those workflows (although I think it would be interesting at some point)

**Comment by ishita9** [comment]
Hi,
I can comment on running Calibration workflow on the cloud. We have run Calibration experiments on cloud before but it was only for a 1-2 basins and on a single c6i compute optimized instances. Also, we were running it via docker on these instances to deal with environment issues. In order to run this scale of an experiment, as @rsignell-usgs suggested, we would have to use multi node implementation/cluster management infra like Kubernetes or potentially run it on hpc instances on AWS. However these multinode/hpc solutions have never been attempted before. Also moving data generated from the experiment back to Denali would also incur additional costs. So within the timeline, considering we need to implement, test and start by next week, going with the cloud solution might not be feasible.

**Comment by rviger-usgs** [comment]
@rsignell-usgs @amsnyder, maybe this experimentation should be part of what we include in our application to the Amazon Sustainable Data Initiative grant program?

**Comment by arezoorn** [comment]
Maybe it would be relevant to mention this here also as this is an ongoing effort. Mike Fienen and us are working on calibration WRF-Hydro with PEST++. It is right now at research phase, but I wanted to mention that Mike is working on the Cloud instance of it, and Ishita and I work on running it on HPC. We really wanted to make good progress to use it for the IWAA, but there is a lot to test and configure with PESP++ and we were not ready to suggest using it for such a big scale calibration effort.

**Comment by rviger-usgs** [comment]
Just an FYI re: `Mike Fienen and us are working on calibration WRF-Hydro with PEST++. It is right now at research phase, but I wanted to mention that Mike is working on the Cloud instance of it, and Ishita and I work on running it on HPC.`

The cloud instance is using HTCondor.

**Comment by rviger-usgs** [comment]
So, unless your current investigation topic works, is the conclusion that for the IWAA production timeline, the workflow will stay as it is currently built? 

Did you also get a chance to discuss w/the ARC group whether reserving nodes to reduce queue times would be a benefit for both/either calibration or production runs?

**Comment by arezoorn** [comment]
So far the only solution we are sure it works is to use one node for a basin calibration. I am going to start some of the larger basins with exclusive nodes and get an estimate on how that will pan out timewise. But if we do not find another solution , we might have to stick to this plan. That means we can only calibration a subset of the 1500 basins at once (Max of 200 given there is only 232 nodes on denali). 

Regarding the reserving nodes, we did not get to it. My apologies, I thought you are going to follow up on that one.  I could leave a message on Teams space if that is desired.

**Comment by arezoorn** [comment]
I am starting the first batch of 50 basins today which are the largest basins we have, I can give an estimate of how long will it take in a day or two. Sorry I do not have a better answer at this point.

**Comment by rviger-usgs** [comment]
@arezoorn no worries--we'll be glad to hear how the first batch goes. 

We talked w/Jeff Falgout today. He is open to the idea of allowing us to reserve nodes for parts of your workflow where it makes sense. It's actually an increased weighting in the queue that we get. It's referred as a QOS (quality of service) weighting. He's on travel next week but will touch base with the staff that was helping you and see if he can think of anything they have not yet suggested--probably won't hear from him until the week after next. We should try to remember to touch base with him when he's back.
