### ISSUE TITLE
Add CONUS404 processing scripts to Github

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#120]
Add scripts used to process various derivate CONUS404 products to this folder: https://github.com/hytest-org/hytest/tree/main/dataset_preprocessing/archive

Ideally there would be 1 directory per dataset in the [CONUS404 versions list](https://doimspp.sharepoint.com/:x:/r/sites/gs-wma-hytest/_layouts/15/Doc.aspx?sourcedoc=%7BD2A499D7-027E-42E5-B0BA-13BA48B32569%7D&file=CONUS404%20versions.xlsx&action=default&mobileredirect=true&CID=A408B70C-6919-4CD8-A73A-02CB1B092245&wdLOR=cD24AE203-57E3-41B5-A1FB-EE0BECCB8766), but I will leave the organization up to you @pnorton-usgs!

These scripts should be actively updated if changes are made.

**Comment by rviger-usgs** [comment]
wanted to add @rmcd-mscb to this, in case the zonalsummary part of the workflow is (currently) separate from the temporal aggregation stuff that @pnorton-usgs has got going.

**Comment by rmcd-mscb** [comment]
@amsnyder @rviger-usgs or @pnorton-usgs - could you give me rights to push a branch and create a merge request?  I've got an archive for the processing of c404 bias corrected daily data to gfv1.1 ready to go :)

**Comment by amsnyder** [comment]
I just invited you to be a member of the org. I think that should give you permission, but let me know if it doesn't.
