### ISSUE TITLE
How do I view the dask dashboard for dask that's running in the users-pangeo kernel?

### ISSUE THREAD

**Issue by sformel-usgs** [hytest-org/hytest#133]
I'm a new user, so this might be pretty simple, but I couldn't figure out how to view the dask dashboard for dask that's running in the users-pangeo kernel in qhub.  So, not spinning up a cluster, just executing dask within a notebook. [This dask doc](https://docs.dask.org/en/stable/dashboard.html) says:

> By default, when starting a scheduler on your local machine the dashboard will be served at http://localhost:8787/status. You can type this address into your browser to access the dashboard but may be directed elsewhere if port 8787 is taken. You can also configure the address using the dashboard_address parameter (see [LocalCluster](https://docs.dask.org/en/stable/deploying-python.html#distributed.deploy.local.LocalCluster)).

So, if I understand correctly, when you're running dask locally then there is a default address to use. But I couldn't figure out something like that in qhub. Anyone able to help me out?

**Comment by rsignell-usgs** [comment]
@sformel-usgs not that normally you don't want to use a local dask cluster on qhub though, as you only have a few cpus and the mounted filesystem is very slow.    Usually it's better to adopt a cloud-native workflow, using a Dask gateway cluster and reading/writing using S3 object storage.   (the dask gateway workers don't see the mounted filesystem).   Does that make sense?

**Comment by sformel-usgs** [comment]
Yes, I think so.  I think I had defaulted to that because it's where I was introduced to dask functions.  Thanks for taking the time to figure this out!
