### ISSUE TITLE
Corrections to HPC instructions

### ISSUE THREAD

**Issue by gzt5142** [hytest-org/hytest#135]
Notes from a test user: 

- [x] I get a error message when I log into Denali and tallgrass:  Unable to locate a modulefile for 'hytest'  I'm not sure if this is what you were referring to, but I can't find the hytest module.
- [x]  When I tried to install jupyter-forward in my base enviroment, it hung up on the solve environment step and I couldn't figure out why. Installing in a fresh environment was the only way to make it work.  Is that a problem is it's not in the base environment
- [x] Run `jupyter-forward denali` appears to work but doesn't accept my active directory password during login.
- [x] I also found, and tried this: https://github.com/hytest-org/hytest/blob/main/environment_set_up/QuickStart-HPC.md but it didn't solve the password error.

**Comment by gzt5142** [comment]
Item two:  installing jupyter-forward on PC.... it does not matter what environment it's installed in.  You just need to have that environment active when you attempt to run `jupyter-forward`

**Comment by gzt5142** [comment]
Item 3:  The ssh to denali and tallgrass... be sure that your 'userid' on your pc matches your 'userid' on the HPC.  For example, when I try to ssh from my pc to tallgrass, the 'userid' is not 'gtrantham', but rather 'gs/gtrantham' (this is my AD user identifier, which includes the gs domain designation). 

You may need to explicitly name your user credential if connecting via ssh. As far as I know, 
jupyter forward can only do this by specifying your 'identity' file (usually in HOME/.ssh).

**Comment by sformel-usgs** [comment]
@gzt5142 I tried out your suggestions, here are some thoughts.

1. Adding those lines to the bashrc allowed me to load and use the hytest environment.
2. I can't seem to get jupyter-forward to ssh into denali. I can ssh in through git bash (how I normally work) and via the conda shell, with the jupyter-forward environment activated.  I confirmed that jupyter-forward is using my .ssh/config file parameters during the ssh, including the identity file. You're correct that my active password id is officially GS\sformel, although I've always used sformel on the HPCs. In any case, it didn't matter which userid I used (I also tried variations with lowercase gs and forwardslash instead of backslash), the result was the same: I was asked for a password, instead of the ssh passphrase, and my active password doesn't do the trick.  Happy to try out any tips you might have!

**Comment by gzt5142** [comment]
> @gzt5142 I tried out your suggestions, here are some thoughts.
> 
> 1. Adding those lines to the bashrc allowed me to load and use the hytest environment.
>
Glad to see it worked out easily.  Good. 

> 2. I can't seem to get `jupyter-forward` to ssh into denali. I can ssh in through git bash (how I normally work) and via the conda shell, with the `jupyter-forward` environment activated.  

Good news and bad news here...  I'm sorry to say that I don't have a lot of guidance about jupyter-forward and authentication.  The jupyter-forward people themselves don't offer much help, saying that the authentication is out of their lane. 

Git bash and the other windows shells obtain your UserID in different ways -- ssh from git-bash will offer a username like `sformel` (which translates correctly to your HPC identity) , while other windows shells will offer `gs/sformel`, which is NOT a valid ID on the HPCs.  When I ssh out of my standard terminal, I specify user explicitly `ssh gtrantham@tallgrass`.  I've never tried that with jupyter-forward, but that's the next step of experimentation in your case... use your username@host instead of just the host when you launch jupypter-forward.

**Comment by sformel-usgs** [comment]
Well, I made enough headway to get `jupyter-forward` functioning, so I'm walking away for today.  But it's still a mystery which bit of code is breaking down.  The solution was to remove the passphrase from the ssh key.  But I'm pretty certain that's not a good idea generally speaking (though please tell me if you think I'm being too cautious).  I did some exploring with `paramiko`, the module underneath `jupyter-forward`.  I was able to ssh into denali as long as I put the passphrase into the `paramiko.connect` function. So, my conclusion is that `jupyter-forward` is asking for the key passphrase when it prompts me for a password, but for some reason isn't passing that to the underlying functions correctly.  But it's possible it's something else, I don't know that much about ssh.

**Comment by gzt5142** [comment]
Well... you certainly took a deeper dive than I was prepared to on that... certainly outpacing what I know about jupyter-forward and authentication. 

If you are finding that jupyter-forward is not behaving as expected, you might find their development team to be a good resource for problem-solving. It might be worth opening an issue with them if you are completely stuck. 

Sorry I am not able to be more helpful on this...

**Comment by sformel-usgs** [comment]
Not a problem! I'll ping the jupyter-forward people and see what they say.
