### ISSUE TITLE
Evaluation Training Compute Platform

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#141]
Question posed to @rsignell-usgs and I by @sfoks:
> Evaluation` is supposed to have a training class on model benchmarking sometime in the spring (Mar 7, 8, 9 tentative dates). We are wondering about what compute platform to run this training on... It would be a mix of lecture/lab (do it yourself)/and talk about it. Though I'm not entirely sure of class size yet or attendee limit we should impose. Depending on the class size, I'm guessing we have some different options for where we should run this class (HPC- tallgrass?, denali? esip-qhub?). What do you two think would be best?

**Comment by amsnyder** [comment]
Rich is probably better equipped to answer this, given that I only have a limited understanding of the process to reserve nodes on the HPCs, but my initial thoughts are

- If you use Denali or Tallgrass, you would probably want to reserve some nodes for each student in advance to actually guarantee that they could participate (but maybe Rich knows better than I do here)
- Cloud sounds good in theory because we don't need to worry about reserving any compute. I'm not sure we want to add a bunch of semi-random people to ESIP QHub. Rich, do you know if there's any chance of having USGS QHub up and running by then?
- What code are you actually running? Could they run it locally? I know this requires them to set up python environments which can cause lots of bumps, but just considering all the options.

**Comment by gzt5142** [comment]
In terms of the notebooks that I had a hand in writing, the cloud platform is going to be better than the HPC.  They were designed and tested for the cluster and gateway config on that platform. 

Those notebooks read and write substantial data using object storage.  Credentials will be a concern for a learning environment, to ensure they can write sample outputs to a suitable spot.

**Comment by sfoks** [comment]
Alright it sounds like cloud is best; either the pangeo chs or Nebari on WMA dev account.  

Should there be a class size limit for this? We would be focusing on the streamflow benchmarking workbooks Gene has rewritten. I could see an attendee writing 200-500 Kb of information, not a whole lot of data being written out per user (ideally).

**Comment by sfoks** [comment]
@rsignell-usgs @amsnyder any updates on getting Qhub on CHS?

**Comment by rsignell-usgs** [comment]
We are hoping to hire a contractor to help with getting this going.   Had a good interview with a candidate yesterday.

**Comment by sfoks** [comment]
For either training environment (pangeo.chs.gov or nebari on chs), would we need all class participants to be added to these groups in particular or would they all just need to get CHS.usgs accounts? I'm trying to remember the process for this...

**Comment by sfoks** [comment]
Talked with Sam Congdon and Courtney Neu, they say pangeo.chs.usgs.gov is okay and to give them a list of participants at least 1 week in advance. Thanks everyone!

**Comment by sfoks** [comment]
The Nebari-workshop training platform worked really well for us! thanks again for setting this up!
