### ISSUE TITLE
conus404 monthly files (zarr and netcdf) have incorrect standard_name for x and y variables

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#143]
The the on-prem conus404 monthly netcdf files the x and y variables have a misspelling in the standard_name. 
```
    double x(x) ;
      x:long_name = "x coordinate of projection" ;
      x:standard_name = "projecton_x_coordinate" ;
      x:units = "m" ;

    double y(y) ;
      y:long_name = "y coordinate of projection" ;
      y:standard_name = "projecton_y_coordinate" ;
      y:units = "m" ;
```

The standard names should be `projection_x_coordinate` and `projection_y_coordinate`, respectively. This causes programs such R, ArcGIS, and QGIS to project the data from these files incorrectly.

**Comment by pnorton-usgs** [comment]
This fix also needs to be applied to the on-prem and cloud monthly zarr datasets.

**Comment by pnorton-usgs** [comment]
The fix has been applied to the on-prem and cloud zarr datasets. 
The on-prem dataset was verified.
Need to add intake catalog entries (see #146) before the cloud dataset is verified.

**Comment by amart90** [comment]
@pnorton-usgs, I tested in R and th e files on caldera worked. See Issue [#142 ](https://github.com/hytest-org/hytest/issues/142#issuecomment-1344739121).

**Comment by padilla410** [comment]
Thank you for the quick fix, @pnorton-usgs!

**Comment by pnorton-usgs** [comment]
That's great to hear. I will close this issue.
