### ISSUE TITLE
Add entries to intake catalog for conus404 monthly datasets

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#146]
Need to add entries to the intake catalog for conus404 monthly datasets: on-prem and cloud zarr.

@rsignell-usgs Should there also be an entry for on-prem netcdf (created for the R folks)?

**Comment by dblodgett-usgs** [comment]
Maybe a slight mischaracterization of what I've said, but ultimately I think this is what should happen. Both GDAL and NetCDF-C are building out zarr client code that can be accessed from R and R can work with xarray via the `reticulate` package.  Working with large NetCDF data in general is hard enough that the slight additional burden of using new or unfamiliar tools isn't really that different.
