### ISSUE TITLE
NHM-PRMS version to which fabric version?

### ISSUE THREAD

**Issue by sfoks** [hytest-org/hytest#149]
I am looking at the NHM-PRMS v1.1 gridMET data on prem (specifically, 'nhm-v1.1-gridmet-byHWobs-onprem' from the intake catalog).

There is no coordinate reference system associated with this data that I can tell...(new to python so point this out to me if its not true). So basically I need to join the correct associated version of the geospatial fabric version with the correct modeling application data (by nhru or nsegment) in order to then generate weights and do some zonal stats.

So I belieevvee nhm v1.1 gridmet is geospatial fabric version 1.1? Is there a cheat sheet somewhere on this? Thanks! @pnorton-usgs

**Comment by pnorton-usgs** [comment]
@sfoks The version information immediately following the 'nhm-' part always references the geospatial fabric version so 'nhm-v1.1-gridmet-byHWobs-onprem' indicates it's the NHM based on geospatial fabric version 1.1 with gridmet forcings used for the calibration. 

You are correct there is no CRS associated with this data. You will need to join it with the matching geospatial fabric using the nhm_id or nhm_seg variables from the model output.

**Comment by sfoks** [comment]
Thank you thank you!

**Comment by sfoks** [comment]
So how will NHM-PRMS forced with CONUS404 be titled? is it still version 1.1?  @pnorton-usgs

**Comment by pnorton-usgs** [comment]
@sfoks The CONUS404 calibrations will use geospatial fabric v1.1; the CONUS GF v2.0 has not been finalized yet. So intake catalog names will be something like `nhm-v1.1-conus404-<calibration>-<onprem, cloud>`.
