### ISSUE TITLE
CONUS404 wrfout ACRUNSF and ACRUNSB description and long_name attributes are wrong

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#154]
@alamotte-usgs @amsnyder The `description` and `long_name` attribute values for variables `ACRUNSF` and `ACRUNSB` are wrong in the wrfout metadata file. This problem exists in the original WRF model output and has propogated through all follow-on datasets that use these variables. See #151, #152, #153 which address the necessary changes to the follow-on datasets. The original CONUS404 wrfout model files will not be changed because of the large number of files produced by the model simulation.

The problem was first reported at https://code.usgs.gov/wma/national-iwaas/NWAA/ws-uncertainty-analysis/-/issues/16

The incorrect attributes are:

```
      ACRUNSF:description = "acccumlated RUNSB" ;
      ACRUNSF:long_name = "Accumulated subsurface runoff" ;

      ACRUNSB:description = "acccumlated RUNSF" ;
      ACRUNSB:long_name = "Accumulated surface runoff" ;

```

The attributes should be:
```
      ACRUNSF:description = "acccumlated RUNSF" ;
      ACRUNSF:long_name = "Accumulated surface runoff" ;

      ACRUNSB:description = "acccumlated RUNSB" ;
      ACRUNSB:long_name = "Accumulated subsurface runoff" ;
```

**Comment by amsnyder** [comment]
Thanks for flagging @pnorton-usgs. @alamotte-usgs - is there anywhere in the metadata xml that would be good to note this error? (since we aren't updating the raw files we publish)

**Comment by amsnyder** [comment]
@pnorton-usgs closing this because we made this update to the metadata - deleted description field, and long_name was updated by you
