### ISSUE TITLE
Fix units for QRFS and QSLAT

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#157]
Units for QRFS and QSLAT are shown as meters when they should be millimeters. This problem exists in the raw wrfout_* model output files so it will need to be overridden in the metadata creation process. This problem was reported by Kyoko Ikeda 2022-08-31 (NCAR).

**Comment by pnorton-usgs** [comment]
Responding to a question from @rviger-usgs:

> was wondering which files this applies to. obviously, it's CONUS404 related. didn't think it was any WRF output, but about updating the metadata model we added, right? so this applies to all USGS-created CONUS404 files?

The incorrect units exist in the original `wrfout_*` model output files which means the WRF code creates the netcdf output files with the incorrect units. In my opinion it's not worthwhile to pull and fix all of the wrfout files, instead we show the correct units in our metadata and make sure the correct units are used in our model products (hourly, monthly, daily).

**Comment by amsnyder** [comment]
@pnorton-usgs - can we close this issue? Looks like you made this update

**Comment by pnorton-usgs** [comment]
Yes we can close it now.
