### ISSUE TITLE
D-score in R?

### ISSUE THREAD

**Issue by sfoks** [hytest-org/hytest#158]
The national assessment team (@tedstets-usgs) would like d-score in R format by the end of January. I see a couple ways of doing this (publishing it). Tim, @thodson-usgs, which option is best?

1. incorporate it into [HyMETT](https://code.usgs.gov/hymett/hymett/-/tree/master/)?
2. generate d-score as it's own R package, with options to add additional error metrics to decompose in future iterations?

I can help with translation into R. Tim, I may need your help checking explanations and deciding which option above is best! I think the notebook @gzt5142 has revised [here](https://github.com/hytest-org/hytest/blob/main/model_evaluation/Metrics_DScore_Suite_v1.ipynb) can be used as a reference for the R translation.

**Comment by thodson-usgs** [comment]
Should be doable. I don't have a strong preference about how to release the R version. D-score for MSE will be simple, and I recommend the R version starts there.  D-score for other metrics like MAE should be simple too, but I probably don't have enough time to complete it by end of January. The harder part might be doing the parallelization in R.

Eventually, I intend to release a stand-alone Python version to use with the workflows that Rich and his team are building, but by all means make an R version and release it however you see fit. Maybe HyMETT first and leave the future open.

**Comment by sfoks** [comment]
Created an issue over in the HyMETT repo, https://code.usgs.gov/hymett/hymett/-/issues/13
