### ISSUE TITLE
hosting data for Delaware Bay

### ISSUE THREAD

**Issue by salme146** [hytest-org/hytest#162]
Hi all, first post here!

I am working on the PUMP project, specifically looking at salinity intrusion in Delaware bay using the COAWST coupled model. I have about ~10 TB of data for several model runs and have been asked about data access from a few scientists. I am wondering how I would store this dataset in a way that it can be accessed for collaboration. 

- Salme (secook@usgs.gov)

**Comment by rsignell-usgs** [comment]
@salme146 I think it would be great to store this on the 100TB allocation we currently have on OSN, and then move it when we get our pod.     We could help show you how to kerchunk it and make it available in the Intake Hytest catalog (or a separate Pump intake catalog if that makes more sense).    @amsnyder and @rviger-usgs what do you think?

**Comment by amsnyder** [comment]
I think the OSN pod could be a viable option. Given that it would take up a non-insignificant portion of the storage space, I think we should ask a few questions though.

@salme146 how long do you anticipate users needing access to this data? Would it be possible to remove the data after a few years?

Also - can you tell me a little more about the people who want access to the data? What languages do they program in? (that might affect our decision about file format)

**Comment by salme146** [comment]
@amsnyder I think it would be great to keep the data there for 3-5 years, then keep initial condition/input files that can be used to recreate the data in the future (if needed, probably not needed). 

The people accessing the data are USGS scientists and academics that I believe will be using both MatLAB and Python.

**Comment by amsnyder** [comment]
@salme146 - thanks that is helpful! I think we need to spend a little time thinking through how we want to manage this resource before we start putting a lot of data on it. Is it ok if we revisit this in a couple weeks? Is there any time constraint on providing access to this data?
