### ISSUE TITLE
Extract footprint and bbox from zarr dataset

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#167]
I am trying to extract the dataset footprint and bounding box from the conus404 dataset (and I'd also like to find a method I can use to extract this information from any zarr dataset). I thought we had added region boundaries to conus404 when @alaws-USGS was implementing the [Abernathy method for region aggregations](https://notebooksharing.space/view/c6c1f3a7d0c260724115eaa2bf78f3738b275f7f633c1558639e7bbd75b31456#displayOptions=), as discussed in #89, but I'm not seeing the bounds defined in the crs. I guess I have two questions:

1. Did we add bounds to conus404?
2. Does anyone have any ideas about the most efficient ways to extract the footprint/bounds from zarr datasets in general? I'm sure I could generate the bbox on my own, but the footprint, I'm not as sure how to approach. For footprint, I'm trying to create a geojson geometry - but if it is really difficult, I think I can drop this information and just use bbox.

**Comment by rsignell-usgs** [comment]
@amsnyder , the Abernathy method requires the `cell_bounds` that describes the cell each data point represents (for CONUS404, it's just a 2km box in x and y, and 1 hour in time.  `cell_bounds` is a CF convention.   For simple uniformly-spaced datasets like this, we can use `cf_xarray` to calculate the `cell_bounds` if not supplied in the original dataset:
```
import cf_xarray
ds = ds.cf.add_bounds(['time', 'x', 'y'])
```
and you can then check to see if that worked using:
```
ds.cf.bounds
```
which produces (for CONUS404):

**Comment by alaws-USGS** [comment]
@amsnyder, @rsignell-usgs has the easiest way to get the bounding box for datasets. I was wondering what the difference in a bounding box and footprint would be? I know that a simplified footprint is a raster's bounding box in some use cases.

**Comment by rsignell-usgs** [comment]
@amsnyder in case you mean you would like a geojson that describes the polygon surrounding the 2D *lon,lat* points, not the rectilinear x,y points, you could generate that by going around the edges of the 2D lon,lat fields, like:
lat[:,0] + lon[-1,:] + ....

**Comment by amsnyder** [comment]
Thank you Rich - this was exactly what I needed...I knew there would be a simple solution!
