### ISSUE TITLE
CONUS404 dimension documentation

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#175]
Some of the CONUS404 variables have a z-axis spatial dimension. I haven't seen these documented anywhere, but I'm happy to be corrected if they are. I would love to see this built into the metadata of the zarr. I also think it could be helpful to create another spreadsheet to document these dimensions for the data release in general. I'm wondering
1. if anyone on our team has this information, or if we need to go the NCAR for this
2. if there is a way to add descriptive metadata about a dataset dimension to the zarrs we have

**Comment by rsignell-usgs** [comment]
@pnorton-usgs , what say ye?   Do you know or do we need to ask NCAR?

**Comment by pnorton-usgs** [comment]
NCAR has a technical report (A Description of the Advanced Research WRF Version 3; http://dx.doi.org/10.5065/D68S4MVH) that goes into the specifics of WRF. In section 3.2 (Spatial Discretization) describes the grid discretization. The non-staggered dimensions are located at the cell center points (mass points) while the staggered dimensions are located at the cell boundaries. 

I've never seen specified descriptions of the dimensions themselves. There is discussion in the WRF documentation about how to unstagger the wind fields onto the mass points. Note that the x_stag and y_stag dimensions in our zarr datasets are west_east_stag and south_north_stag, respectively, in the wrfout files.

To add descriptive information to the staggered variables we would need to create coordinate variables for them. I would check with NCAR and see if they have some further documentation about the staggered dimensions and how to work with the variables that use them.

**Comment by amsnyder** [comment]
I am closing this out - I was looking for descriptions of the dims to add in to STAC, but I'll just leave the descriptions out since it'll be a bit of lift and it isn't a required piece of metadata.
