### ISSUE TITLE
Writing to OSN for workshop participants

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#178]
It would be nice to be either to set bucket policy or establish temporary credentials that would allow workshop participants to write to OSN for the duration of the workshop.   

It does look like bucket policies can be set: 
https://docs.ceph.com/en/pacific/radosgw/bucketpolicy/

**Comment by amsnyder** [comment]
Thanks @rsignell-usgs! I mentioned this in Gene's PR, but I guess I need an account set up, right? I've not touched the pod yet! I should probably have the highest level of permissions if I need to manage this resource. I'd like to jump on the phone with you when you create my account so I can see how you do it.

**Comment by amsnyder** [comment]
@sfoks - the new OSN pod bucket is set up and I can read from and write to it. I was testing this from pangeo.chs.usgs.gov, so it should work fine for your tutorial. When you are ready to test your notebooks in the pangeo.chs.usgs.gov environment, let me know. I can share the credentials that students will use, and we can make sure all the write out from your notebooks works.
