### ISSUE TITLE
Fill in pangeo compute set up

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#190]
This file needs to be updated to provide more instruction to a user: `environment_set_up/QuickStart-Cloud-pangeo.chs.usgs.gov.md`. Most importantly, the process for requesting a user account needs to be added. It would also be helpful to add screenshots and instuctions for using the terminal and cloning our repo into a user's space.

**Comment by gzt5142** [comment]
@amsnyder 
I do not have an account on that system.  Nor do I know how to go about getting one.  
Can you give me some context or a starting direction?

**Comment by rsignell-usgs** [comment]
@gzt5142 I thought we had these directions somewhere.  You sign up on the CHS support page.

**Comment by amsnyder** [comment]
I think we got these instructions added into to an open PR - but would like to hear from you @rsignell-usgs on how we go about submitting a request to update the kernel. Do you submit a ticket to CTek's Jira board?

**Comment by gzt5142** [comment]
https://support.chs.usgs.gov/display/CHSKB/Pangeo+Framework

**Comment by gzt5142** [comment]
I am having a heck of a time getting the cluster to work right on pangeo.   I can spin up a `LocalCluster`, which works for simple demos, but not for massive compute operations. 

Currently trying to get `kubecluster` configurations to work, but so far no joy.   The struggle continues.

**Comment by rsignell-usgs** [comment]
Should be working now.  This wasn't your fault -- another use was using the max number of instances we allow

**Comment by gzt5142** [comment]
closed by #189
