### ISSUE TITLE
move TestData.csv

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#198]
I'm not sure what this file is for:
https://github.com/hytest-org/hytest/blob/main/essential_reading/DataSources/TestData.csv

I think it was maybe being used in a workflow somewhere, but can't remember where. I'm wondering if we can move this data to the OSN pod?

**Comment by gzt5142** [comment]
https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/ReChunkingData.ipynb

**Comment by gzt5142** [comment]
I don't have a strong opinion on where it is stored.  
But if you move it, that rechunking notebook should be updated to reflect its location.

**Comment by amsnyder** [comment]
I see that notebook references `TestData.zarr` which is stored in that same folder - but I don't see `TestData.csv` in that notebook.

**Comment by gzt5142** [comment]
Ah yes... I absolutely missed that. 

This csv is a vestige of `model_evaluation\tutorials\nwm_streamflow\NWM_Benchmark_SampleData.csv`
The `TestData.csv` can be deleted, as it has been replaced with `NWM_Benchmark_SampleData.csv`.
 
But this brings up another point... do you want `TestData.zarr` to be moved to other storage or remain in this repo.
