### ISSUE TITLE
Add essential_reading/DataSources/README

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#199]
referenced in JupyterBook - can you add a README to describe the files in this folder?

Open a new PR for this (not the JupyterBook PR so we can review/merge it in even if the JupyterBook PR is still open.

**Comment by zdefne-usgs** [comment]
Thanks for the documentation! In the README.md the link to 
https://github.com/hytest-org/hytest/blob/5c041cfb45e8fd39ba9bc0cd32850f6990db5b73/essential_reading/DataSources/Data_S3.ipynb
should be 
https://github.com/hytest-org/hytest/blob/5c041cfb45e8fd39ba9bc0cd32850f6990db5b73/essential_reading/DataSources/Data_S3.md
