### ISSUE TITLE
CONUS404 panel app location

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#2]
Should we move the CONUS404 panel app into our Github? Right now it lives [here](https://github.com/amsnyder/Holoviz-Demos).

We could make a folder called `apps` and move it in there, along with any future apps we create.

We could also put it in the `data_access` folder, but this might be confusing because we don't expect our users to use the notebook for access, right? I was imagining the `data_access` folder has notebooks we want a user to clone and work directly in.

**Comment by rsignell-usgs** [comment]
@amsnyder I think you are likely right -- the graphics displayed in the apps might look quite similar to cells in data_access notebooks but they will be customized enough that they should live in their own folder.   And yes, let's move the CONUS404  app notebook here.   We will have to modify our Panel app DOCKERFILE so that it's pulling from multiple repos, but that's fine.

**Comment by rsignell-usgs** [comment]
The latest version of the conus404 app is at: https://jupyter.qhub.esipfed.org/hub/user-redirect/lab/tree/shared/users/rsignell/notebooks/COAWST/CONUS404_Panel_App.ipynb

@alaws-USGS  or @gzt5142 we could really use a calendar pick widget but I couldn't figure out how to do it.   There is some discussion here: https://github.com/holoviz/panel/issues/1975, https://discourse.holoviz.org/t/elegant-date-and-time-picker/1262

**Comment by gzt5142** [comment]
@rsignell-usgs Are you looking for something specific to holoviz? Andrew is the holoviz guy, so he may have the slick answer. . . 

Generic jupyter/ipython widgets can do this fairly well for broad use-cases outside of visualization widgetry... see: 
```
https://github.com/USGS-python/hytest_notebook_tutorials/blob/dev/doc/parts-bin/temporal-range.ipynb
```

**Comment by alaws-USGS** [comment]
Here is my solution for the widgets:
https://jupyter.qhub.esipfed.org/hub/user-redirect/lab/tree/shared/users/alaws/CONUS404_Panel_App.ipynb

**Comment by gzt5142** [comment]
@amsnyder is this issue closeable?

**Comment by alaws-USGS** [comment]
From weekly meeting on 4/3/23: Leave open as reference for incoming cloud engineer.
