### ISSUE TITLE
essential_reading/ParallelProcessing/README

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#200]
referenced in JupyterBook - can you add a README to describe the files in this folder?

Open a new PR for this (not the JupyterBook PR so we can review/merge it in even if the JupyterBook PR is still open.

**Comment by gzt5142** [comment]
Most of these files (all but one, actually) are deprecated, given the work being done on the cluster helpers in another branch. 

The one remaining file (`Parallal_Dask.ipynb`) has been moved up and the `ParallelProcessing` folder removed.
