### ISSUE TITLE
Move CONUS404 tutorial material

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#214]
- [ ] Move both of these files in [dataset_preprocessing/tutorials/CONUS404](https://github.com/hytest-org/hytest/tree/main/dataset_preprocessing/tutorials/CONUS404) into [model_evaluation/tutorials/CONUS404](https://github.com/hytest-org/hytest/tree/main/model_evaluation/tutorials/CONUS404).
- [ ] delete [conus404_analysis.ipynb](https://github.com/hytest-org/hytest/blob/main/model_evaluation/tutorials/CONUS404/conus404_analysis.ipynb) from model_evaluation folder because it has been replaced

**Comment by amsnyder** [comment]
@alaws-USGS - do you think you could do this in the next couple of days? I'm looking through our content for the JupyterBook TOC and want to make sure everything is in the right place before Gene adds additional content to the TOC.

**Comment by alaws-USGS** [comment]
@amsnyder due to the number of ongoing steps with these notebooks, these were going to be moved over after the completion of the analysis notebook and before it went out for review, which is about a month out.

**Comment by amsnyder** [comment]
Ok - thanks for letting me know! I'll just exclude any CONUS404 tutorials from the JupyterBook TOC for now.
