### ISSUE TITLE
Move rechunking data tutorials

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#216]
I will update location of [TestData.zarr](https://github.com/hytest-org/hytest/tree/main/dataset_preprocessing/TestData.zarr) to OSN pod and let @gzt5142 know.

@gzt5142 will update the filepaths in his rechunking notebooks and delete TestData.zarr from Github.

@gzt5142 will move [ReChunkingData,ipynb](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/ReChunkingData.ipynb) and [ReChunkingData_Cloud.ipynb](https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/ReChunkingData_Cloud.ipynb) into `dataset_preprocessing/tutorials/rechunking`.

**Comment by gzt5142** [comment]
New branch `gt-216-relo-chunking-demo` to hold changes related to this issue.

**Comment by gzt5142** [comment]
Although... using the food analogy from our meeting, these would be tutorials rather than demos.

**Comment by amsnyder** [comment]
let's make them tutorials then!

**Comment by gzt5142** [comment]
OK... the stuff is in the right spot (tutorials).  Once the testdata.zarr gets moved to a storage toaster, I can refactor to use S3. 

Right now, it reads from local disk and writes to local disk (`/tmp/output.zarr`). That *should* still work in these new locations, but I will thoroughly test when the S3 storage options are fixed. 

Which raises an interesting question.... do we want to write to S3 or to 'local' disk?  It's not that much data, so local will work most anywhere. If we want these tutorials to write to S3, then we need to set up a writable place where the demo can stash outputs .

**Comment by amsnyder** [comment]
I like the idea of coding up both options with the default to local disk. Many users might not have credentials, and we still want them to be able to test out the tutorial. But we could have a commented out option to write to the OSN pod scratch space that could be used for people who do have credentials.

**Comment by amsnyder** [comment]
@alaws-USGS - is it ok if I move the TestData.zarr file into `rsignellbucket2/hytest/tutorials`? I think you are the creator of the data files in there, and I want to make sure it doesn't get wiped because you don't know what the file is!

**Comment by gzt5142** [comment]
Maybe we could reconsider the filename... from `TestData.zarr` to `ReChunking_Demo_Data.zarr`  or similar?

**Comment by amsnyder** [comment]
Actually it might be nice to mirror our Github repo on the OSN pod to some extent. I'm thinking I put `TestData.zarr` in either (1) `rsignellbucket2/hytest/tutorials/dataset_preprocessing/ReChunking_Demo_Data.zarr` or (2) `rsignellbucket2/hytest/dataset_preprocessing/tutorials/ReChunking_Demo_Data.zarr`.

Then @alaws-USGS could do similar. Any preferences on option 1 or 2?

**Comment by gzt5142** [comment]
> Any preferences on option 1 or 2?

No preference.

**Comment by amsnyder** [comment]
Let's see if Andrew has a preference. @gzt5142 are you ok with calling the file `ReChunking_Tutorial_Data` since we just decided this is a tutorial?

**Comment by amsnyder** [comment]
I went ahead and moved the data and put it in intake in #221. Since we are using intake, if I update the filepath later, it shouldn't affect your workflow. Go ahead and test out the OSN pod data, and feel free to delete the zarr file from Github if it is working for you!

**Comment by alaws-USGS** [comment]
@amsnyder of the two options, I would say that 1 more mirrors our current directory structure on GitHub.

**Comment by amsnyder** [comment]
@alaws-USGS - shall we move these 3 files into `rsignellbucket2/hytest/tutorials/model_evaluation`?:
![image](https://user-images.githubusercontent.com/30877272/217624652-88ee5c66-924e-42bb-8178-d3a59bfd9a6a.png)

**Comment by gzt5142** [comment]
The rechunk demo using `TestData.zarr` has been refactored to use the intake catalog. 

however... I have found that the cluster-aware rechunk demo that used to work on ESIP/QHUB is not now working on the new Nebari system.  

Debugging now....

**Comment by gzt5142** [comment]
The failing workflow for the full-scale rechunk demo was due to a library version (notably, zarr and fsspec).  I think we've got that sorted out, due to a lot of effort from @rsignell-usgs . 

I need to debug and optimize one last thing, then re-run this demo workflow for the jupyterbook. Then I think we can finally merge and close this issue.
