### ISSUE TITLE
Transfer CONUS404 hourly data to OSN pod

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#225]
I've begun transferring the hourly conus404 data from Caldera to the OSN pod with the following command:
`nohup aws s3 sync /caldera/hytest_scratch/scratch/conus404/conus404_hourly.zarr/ s3://rsignellbucket2/hytest/conus404/conus404_hourly_202302.zarr/ --endpoint-url https://renc.osn.xsede.org --profile osn-renc`

This will take up about 70 TB of storage space.

FYI @rsignell-usgs

**Comment by amsnyder** [comment]
Data transfer completed on March 6, so it took about 3 weeks to transfer 70TB from Caldera to the OSN pod.

**Comment by amsnyder** [comment]
I added this in to the CONUS404 intake catalog in #243.

**Comment by sfoks** [comment]
does Globus transfer from Caldera to OSN?

**Comment by amsnyder** [comment]
I'm not sure - I used aws sync and Rclone is another option - I imagine Globus would work too!

**Comment by rsignell-usgs** [comment]
Globus should work transfering to s3 endpoints but I seem to remember that Parker found some issues:  is that true @pnorton-usgs ?

**Comment by rsignell-usgs** [comment]
Parker said when he tried Globus it was slow, perhaps it doesn't have a parallel option or we didn't know how to enable?
