### ISSUE TITLE
Refactor conus404_explore for cluster

### ISSUE THREAD

**Issue by gzt5142** [hytest-org/hytest#236]
Per request from @rsignell-usgs , refactor `conus404_explore.ipynb` to 
make use of cluster start helpers.

Will demo their use in the nebari environment, but will include stubs so 
that the reader can switch to another if they want.

**Comment by gzt5142** [comment]
First draft available as a shared notebook at: 
https://nebari.esipfed.org/hub/user-redirect/lab/tree/shared/users/gzt5142/hytest/dataset_access/conus404_explore.ipynb

**Comment by gzt5142** [comment]
@amsnyder  
Does this change need to wait for something you're doing with CONUS? I think I remember some changes to intake/stac in the works.  Should I wait to merge this until after you're done or can I push it now?

**Comment by amsnyder** [comment]
You can push it - I'm a little backed up and I will update this notebook when i update the intake catalog if it is needed
