### ISSUE TITLE
move QuickStart-General

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#265]
I'm not sure how this file ties in with our other environment set up files: https://github.com/hytest-org/hytest/blob/main/environment_set_up/QuickStart-General.md.

Is it linked from other files? Should the information within it be contained in the README of environment set-up, if it is relevant to all environments? https://github.com/hytest-org/hytest/blob/main/environment_set_up/README.md

**Comment by gzt5142** [comment]
This was a specific request from @rsignell-usgs for generic instructions for non-USGS folk. I don't have any attachment to where it goes.  Nothing links to it that I am aware of.

**Comment by rsignell-usgs** [comment]
Nice work Gene!
