### ISSUE TITLE
open issues for all markdown files needed for JupyterBook TOC

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#276]
Open and issue for each additional markdown file needed by the JupyterBook TOC so that we can assign people to build this content. This task is related to #118.

**Comment by gzt5142** [comment]
* About 

## Environment Set-Up

* Compute Environment
  * QuickStart-Cloud-Nebari
  * QuickStart-Cloud-pangeoCHS
  * OpenOnDemand
  * JupyterForward
  * StartScript
* Starting A Cluster
  * Help_AWS_Credentials
  * Start_Dask_Cluster_Nebari  
  * Start_Dask_Cluster_PangeoCHS
  * Start_Dask_Cluster_Denali
  * Start_Dask_Cluster_Tallgrass

## Getting Started

* ReadingsTutorials
* DataSources
  * Data_APIs
  * Data_S3
  * Data_STAC
* Parallelism with Dask
* "Chunking" data
  * ReChunkingData
  * ReChunkingData_Cloud


## Dataset Access
* hytest catalogs
  * catalog
  * sub-catalogs
* CONUS404 Access
  * Explore CONUS404


## Model Evaluation Tutorials
* metrics
  * Metrics_DScore_Suite_v1
  * Usage_DScore_Suite_v1
  * Metrics_StdSuite_v1
  * Usage_StdSuite_v1
* NWM StreamFlow
  * 01_Data_Prep
  * 02_Analysis_StdSuite
  * 02_Analysis_DScore
  * 03_Vizualization


## Supplementary
  * CONTRIBUTING
  * LICENSE

**Comment by gzt5142** [comment]
Some nomenclature: 

In the above sample (the current state of the TOC, more or less), 

* "Parts" are bold and big (Supplementary, Environment Set-Up, ...)
* "Chapters" are the first level of bullet list (black dots)
* "Sections" are the next level (white dots)
* "Sub-Sections" are not included, as we don't have any of those yet (and may not).
