### ISSUE TITLE
cf_xarray can't identify latitude and longitude in CONUS404

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#279]
`cf_xarrray` can't identify the latitude/longitude variables in CONUS404 with `ds.cf["latitude"]` and `ds.cf["longitude"]`.

If you check the [methods for cf_xarray](https://cf-xarray.readthedocs.io/en/latest/coord_axes.html), you will see that we do not include `standard_name`, our `long_name` is not exactly 'longitude'/'latitude', and there are multiple variables with the unit degree_east/degree_north. See below for longitude printout of 3 conflicting variables:
![image](https://user-images.githubusercontent.com/30877272/230500217-a4463c92-6839-494c-b082-4cef8d968c15.png)

Is this a know/accepted issue or could we update the CONUS404 metadata to be more compatible with `cf_xarray`?

**Comment by rsignell-usgs** [comment]
long_name has no meaning in CF, we should definitely be including "standard_name" for time, longitude and latitude!

Super easy to change since we have Zarr format!

**Comment by amsnyder** [comment]
Do you have a notebook that represents how to do this? I think I've seen the process, but it's been awhile, and I'd like to try to update the metadata to refresh myself (and then add the notebook to our repo as a demo).

**Comment by pnorton-usgs** [comment]
@amsnyder , @rsignell-usgs  I've updated the on-prem metadata for the CONUS404 hourly, monthly, daily, and daily_xtrm datasets to include standard_name on the lat and lon variables. If this works correctly now then we can push the zmetadata files to their cloud locations.

**Comment by amsnyder** [comment]
I tested the dataset on Caldera with `ds.cf['latitude']` (like @rsignell-usgs originally used) - I think cf_xarray allows **all** coordinates that match **any** of the criteria specified in the link above to be returned (using standard_name, long_name, and units), so I am getting back latitude, lat_u, and lat_v because they all have the unit degree_north.

However, I can get just the coordinate lat back if I use `ds.cf.standard_name['latitude']` so I think that addition should work.

However, I think you accidentally labeled lon_u with the standard_name 'longitude' instead of lon. Could you fix that when you get the chance and I'll test again @pnorton-usgs ?

**Comment by pnorton-usgs** [comment]
@amsnyder I took a look at the zmetadata but the lon variable is correctly marked with the standard_name attribute; the lon_u variable does not have that attribute. The `ds.cf.standard_names` command returns:
```python
{'latitude': ['lat'],
 'longitude': ['lon'],
 'time': ['time'],
 'projection_x_coordinate': ['x'],
 'projection_y_coordinate': ['y']}
```

**Comment by amsnyder** [comment]
I just tested and it seems to be working. Feel free to push the changes up to the cloud dataset!

**Comment by pnorton-usgs** [comment]
@amsnyder - I've pushed the zmetadata updates for hourly (cloud and osn), monthly (cloud), and daily (cloud). I verified that each dataset, when opened, has standard_name for latitude and longitude.

**Comment by amsnyder** [comment]
Thanks @pnorton-usgs !
