### ISSUE TITLE
How does aggregation fit in to current evaluation workflows?

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#3]
For gridded datasets that we want to aggregate to some spatial unit (and possibly store on S3 for our users to access) - does this fit in to the model evaluation workflow structure (maybe in notebook 1)? Or is this a new notebook that is like notebook 1.5, and notebook 1 is just for rechunking data?

**Comment by sfoks** [comment]
I think we can close this issue now? 

I envision this aggregation of data as being in /preprocessing. @alaws-USGS has been working on the spatial aggregation piece and I think that work will be in data preprocessing?

**Comment by alaws-USGS** [comment]
That is correct @sfoks. This will be done in preprocessing for the datasets to be ready to just drop into analysis.

**Comment by amsnyder** [comment]
I agree with this. Closing the issue.
