### ISSUE TITLE
correct paths and links for tutorials/nwm_streamflow

### ISSUE THREAD

**Issue by gzt5142** [hytest-org/hytest#309]
A few paths are incorrect in these notebooks -- a hold-over from before jupyterbook became the publication path.  A few links are to `/dev/null` as placeholders to the final link target (once they were known).  

to-do: 

- [ ] Correct paths in TOC
- [ ] Find and fix `/dev/null` link targets in notebooks
- [ ] re-compile and re-build the jupyterbook with corrected links. 

--gt

**Comment by gzt5142** [comment]
I opened this with the expectation of taking out the null links... because I remember them being in there. But now I can't find.  @amsnyder did you already fix this?

**Comment by amsnyder** [comment]
Yes I think so! I fixed all the missing links in the Jupyter notebooks that get pulled into the JupyterBook.

**Comment by gzt5142** [comment]
OK then... closing this as having already been done.  Thanks amelia.
