### ISSUE TITLE
OGC Metadata Sprint (including STAC!) Register by 9/11

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#36]
Joint OGC - ISO/TC 211 Code Sprint. - FREE/ Hybrid. Register by 9/11
    
[Metadata Code Sprint (ogc.org)](https://developer.ogc.org/sprints/18/)

Chance to sign up to be mentored also.   @amsnyder ?  Others?

**Comment by amsnyder** [comment]
Thanks Rich - I will attend the informational session on 9/8 to learn more. I will most likely participate in some of the mentoring streams, but not the full code sprint. I'll try to tune in to the final demos too to see what everyone produced.

**Comment by amsnyder** [comment]
I attended the mentoring sessions and learned a couple things. I asked Matthias Mohr, who presented on STAC, about handling zarr files in STAC and he said there is still some back and forth and I should talk to the zarr community to see their current recommendation. He suggested I reach out to Ryan Abernathey (rpa@ldeo.columbia.edu) to see if he knows who might have the answer. I will reach out, but closing this issue as the spring is nearly over.
