### ISSUE TITLE
Add demo showing how to pull PRISM data from web service and rechunk

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#366]
I think we will add in here: https://github.com/hytest-org/hytest/tree/main/dataset_preprocessing/demos

**Comment by amsnyder** [comment]
@alaws-USGS - I think you completed this right? can you drop the links in here.

Don't close the issue yet - I want to see if they should go into the JupyterBook before we close it out.

**Comment by alaws-USGS** [comment]
@amsnyder the link you have above is the link for the ones I completed

**Comment by amsnyder** [comment]
That folder contains a few demos - is is this one: https://github.com/hytest-org/hytest/blob/main/dataset_preprocessing/demos/pyPRISM_daily_byYear.ipynb 

And also these: https://github.com/hytest-org/hytest/tree/main/dataset_preprocessing/demos/asynchronous_download

**Comment by amsnyder** [comment]
Is there anything left to complete? on this issue?

**Comment by alaws-USGS** [comment]
Nope, this can be closed!
