### ISSUE TITLE
Develop list of features

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#376]
- [ ] Review HydroInspector and create list of features that it includes
- [ ] Update features not in [Sydney's tracking document](https://doimspp.sharepoint.com/:w:/r/sites/gs-wma-hytest/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B100073b6-48a3-4e80-b065-e834f31c94e9%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1&ovuser=0693b5ba-4b18-4d7b-9341-f32f400a5494%2Casnyder%40usgs.gov&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA5MjkxMTIwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)
- [ ] Identify features to include in minimum viable product

**Comment by alaws-USGS** [comment]
- [ ] Review HydroInspector and create list of features that it includes
- [ ] Update features not in [Sydney's tracking document](https://doimspp.sharepoint.com/:w:/r/sites/gs-wma-hytest/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B100073b6-48a3-4e80-b065-e834f31c94e9%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1&ovuser=0693b5ba-4b18-4d7b-9341-f32f400a5494%2Casnyder%40usgs.gov&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA5MjkxMTIwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)
- [ ] Identify features to include in minimum viable product

**Comment by amsnyder** [comment]
Feature list drafted [here](https://doimspp-my.sharepoint.com/:o:/r/personal/alaws_usgs_gov1/_layouts/15/Doc.aspx?sourcedoc=%7B39093A69-3E4B-4BDE-95AB-956758A8EF87%7D&file=HyTEST%20-%20Andrew&action=edit&mobileredirect=true&wdorigin=Sharepoint&RootFolder=%2Fpersonal%2Falaws_usgs_gov1%2FDocuments%2FHyTEST%20-%20Andrew&d=w39093a693e4b4bde95ab956758a8ef87&e=5%3Ad50d71bbd0b4471db280c1d5a4669f86&sharingv2=true&fromShare=true&cid=d5d45654-1e08-4cb0-8fce-bb092b3cfaa7) and shared with Roland on 3/13/24
