### ISSUE TITLE
Create report on pangeo-forge bakery vs. regular rechunking workflow

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#383]
- How does the workflow for each compare? (standardization, level of effort, format, etc.)
- What cloud resources will we be using to deploy the bakery? (this can help us estimate cost)
- What code/repos do we need to build this? How will we need to adapt/modify each of these?

**Comment by amsnyder** [comment]
pangeo-forge bakery has standardized template for use to fill in to rechunk a dataset

**Comment by thodson-usgs** [comment]
In principle, it looks very useful if we can jump the starting hurdle. 
I'm working on a recipe to process SSEBOP data for @kjdoore. 
The recipe was easy but I'm still working through [issues](https://github.com/thodson-usgs/staged-recipes/issues/1)

**Comment by thodson-usgs** [comment]
Still stuck, so I create a [recipe PR](https://github.com/pangeo-forge/staged-recipes/pull/262) to pangeo-forge. I'll follow up in their coordination meeting on Monday.

**Comment by thodson-usgs** [comment]
The SSEBOP recipe seems to be working now, thanks to some assistance from the pangeo-forge community.

All-in-all the recipes are fairly straightforward. Debugging Beam pipelines was challenging but I suspect that will get easier with time.

Pros: community of experts willing to help (esp if we contribute); recipes run a variety of "runners"; easier to manage large projects

Cons: Beam is harder to use than a notebook; Pangeo-forge documentation is incomplete; may create some technical lock-in or necessitate external support
