### ISSUE TITLE
prec_acc_nc: convective vs. non convective rainfall? 

### ISSUE THREAD

**Issue by tpartrid** [hytest-org/hytest#410]
Hi! 

I've been processing `conus404-hourly-onprem` to force an offline version of WRF-Hydro. I'm wondering if the conus404 `prec_acc_nc` variable contains both convective and non-convective rainfall from WRF. It was my understanding that these are separated within WRF output files, but I don't see a corresponding `prec_acc_c` variable within the conus404 dataset.

Thanks for your help!

**Comment by amsnyder** [comment]
Hi @tpartrid - thanks for the question! Would you mind opening this up as a discussion here: https://github.com/hytest-org/hytest/discussions/categories/dataset-questions?

We are trying to use this discussion space more to have discussions/answer questions and use our issues space to track work that needs to be done.

I will tag someone who can help answer this question once you open the new discussion thread.
