### ISSUE TITLE
Add 2021-2022 CONUS404-BA data to zarr

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#444]
Add additional data for 2021 through 2022-09-30 to the conus404 bias-adjusted dataset

**Comment by pnorton-usgs** [comment]
@amsnyder - The conus404 bias-adjusted hourly and daily on-prem datasets have been updated through 2022-09-30.

**Comment by pnorton-usgs** [comment]
@amsnyder - was the updated CONUS404-BA uploaded to the OSN pod? If so we can close this issue.

**Comment by amsnyder** [comment]
Looks like the OSN pod is missing the last chunk so a few days of data aren't copied yet...I am copying it over now and will close this issue once it is done.

**Comment by amsnyder** [comment]
Data is done transferring so I am closing
