### ISSUE TITLE
Move ebdpy helpers to esip-qhub Github

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#48]

**Comment by rsignell-usgs** [comment]
@gzt5142 , I'd like to install the helpers on esip-qhub.   How to proceed?

**Comment by gzt5142** [comment]
in the hytest_tutorial_notebooks repo (which is being deprecated, yes?)... there's a folder `lib`, and that stuff is in there.   In the notebooks that I've been playing with, I just manipulate sys.path to include that folder -- I have not been adding to the standard environment via pip, conda, poetry, or similar....  

I notice that you've got some other specialty libs in /usr/share/lib (or a path to that effect)... perhaps we can just put these alongside.

Let me re-bundle for this sort of side-load in a shared space, and I'll get you a link to a zip or something.  I'm near the end of my day today... will prioritize for tomorrow.

**Comment by rsignell-usgs** [comment]
@gzt5142 , could we add something to users startup file (e.g. ~/.bash_profile)
``` python
 import sys
# adds the dir/folder to the system path search list
libDir = r'/shared/users/lib'
if libDir not in sys.path: #but only if it isn't already there...
    sys.path.append(libDir)
```

**Comment by gzt5142** [comment]
I think this will do it: 
```
export PYTHONPATH="$PYTHONPATH:/shared/users/lib"
```
Let me test and verify.

**Comment by gzt5142** [comment]
Looks like the `.bashrc` is not user-editable.  It is a symlink to a file established by the hub somehow.  I'm weak on juypyterhub, so need to learn a bit more. 

The more practical solution would actually be to put a symlink or redirect file in the site-packages folder within the pangeo python folder structure.  I don't know if we get to edit files in those folders or not.

**Comment by gzt5142** [comment]
Looks like admin could do this -- not sure if you have that permission... 

<https://jupyterhub.readthedocs.io/en/stable/reference/config-reference.html>

Looking for `c.Spawner.environment` and `c.Spawner.env_keep`


The way I read this, setting that option will set the PYTHONPATH for all shells and servers spawned.

**Comment by gzt5142** [comment]
Maybe a better solution... again, I don't know what admin privileges we have vs what we'd need to do this. 

https://github.com/jupyterhub/the-littlest-jupyterhub/issues/308

**Comment by gzt5142** [comment]
https://github.com/jupyterhub/jupyterhub/issues/227

**Comment by gzt5142** [comment]
This feels like a larger question that we should answer for the HPC platform as well. 

Do we want a library installed somewhere on the file system?  if so, where? 

One other option for helpers that we talked about a while back was a common 'setup' notebook to source into other notebooks via a `%run` magic. See #25

**Comment by gzt5142** [comment]
The take-away that I got from our meeting yesterday is that we'd like to use jupyter 'magics' rather than create formal packages for these common/helper bits of code.  I will refactor the cluster helper on ESIP/QHUB to see how that works compared with the module approach we had been experimenting with.

**Comment by gzt5142** [comment]
I've got a mock-up of how the magic methods would be used on esip/qhub

https://jupyter.qhub.esipfed.org/hub/user-redirect/lab/tree/shared/users/gzt5142/ClustDemo.ipynb

Looking for feedback to see if that is the right direction or if I should explore other options.
