### ISSUE TITLE
Update CONUS404 on S3 to include x,y data (that is already on Caldera)

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#49]
Ensure that there are projected coordinates on all CONUS404 datasets

**Comment by gzt5142** [comment]
I would love to attend this session also. And perhaps we can capture the essential knowledge as a pre-processing how-to document to live along side re-chunking and similar.

**Comment by alaws-USGS** [comment]
Sounds good. Should we schedule this for next week sometime?

**Comment by rsignell-usgs** [comment]
Yes, would Monday work?

**Comment by gzt5142** [comment]
Monday -- wide open except for the HyTest check-in at 11 central. 
Tuesday -- Blocked out from 1 to 2 central time, and from 3-4. otherwise open.

**Comment by rsignell-usgs** [comment]
Folks, here's my attempt to capture the work we did in the meeting today: 
https://nbviewer.org/gist/4db31799d2b677fb54f89be6ca3328c4

I'm happy to report that it seem to be working just fine!
![Screenshot 2022-09-12 122553](https://user-images.githubusercontent.com/1872600/189728820-6d3d322c-a334-4afc-a726-2cd12d7cad47.png)

**Comment by gzt5142** [comment]
Thanks for the demo today. It was very informative.... and I learned a couple of tricks that helped me figure out the problems I was having with #41.  Two birds/stone today.
