### ISSUE TITLE
SLURM cluster guidance on USGS HPCs

### ISSUE THREAD

**Issue by theobarnhart-USGS** [hytest-org/hytest#510]
I have started using your SLURM cluster guidance (https://github.com/hytest-org/hytest/blob/main/environment_set_up/Start_Dask_Cluster_Tallgrass.ipynb) for Dask work on the USGS HPCs via the OnDemand web portal. When I do this, request a large allocation for interactive work (e.g. 128 cores, 256 gb ram on Hovenweep). Then I start a SLURM cluster in my notebook and start working with C404 data. Is the SLURM cluster hitting the cores I have requested through OnDemand or is it submitting new jobs to the HPC scheduler? Is there a best practice for using this kind of Dask cluster on USGS HPCs? I attempted to see what was going on with `top`, but was not very successful.

**Comment by pnorton-usgs** [comment]
When you use dask SLURMCluster new jobs are submitted to the SLURM scheduler; so they would be in addition to what you requested through OnDemand. Typically I will be running my notebooks on a few cores and then use SLURMCluster to fire off whatever additional resources I need for dask.

**Comment by amsnyder** [comment]
@pnorton-usgs correct me if I am wrong, but I think you can use a [local cluster](https://hytest-org.github.io/hytest/environment_set_up/Start_Dask_Cluster_Desktop.html) to use resources you have already requested through OnDemand.

I will try to add this info to our JupyterBook today to help other users.

**Comment by amsnyder** [comment]
@theobarnhart-USGS I added this information to our JupyterBook in the section talking about how to connect to the HPCs with OnDemand: https://hytest-org.github.io/hytest/environment_set_up/OpenOnDemand.html
