### ISSUE TITLE
Accessing -onprem datasets on Tallgrass

### ISSUE THREAD

**Issue by putmanannie** [hytest-org/hytest#526]
I am attempting to access 'nhm-v1.1-c404-bc-byHW-onprem' using hytest workflows while in an interactive session on Tallgrass. While I am not on the HYTEST server, I have a (nearly) equivalent environment (just a few extra packages) that I'm using for this work. A code snippet that's basically copied from the HYTEST example notebooks:

`hytest_cat = intake.open_catalog("https://raw.githubusercontent.com/hytest-org/hytest/main/dataset_catalog/hytest_intake_catalog.yml")

cat = hytest_cat['nhm-v1.1-c404-bc-catalog']
dataset = 'nhm-v1.1-c404-bc-byHW-onprem'

ds = cat[dataset].to_dask()` 

when I run this I get "FileNotFoundError: [Errno 2] No such file or directory: '/caldera/hovenweep/projects/usgs/water/impd/hytest/nhm/nhm_v1.1/c404-bc_byHW/nhm_v1.1_c404-bc_byHW_combined.json/.zmetadata'"

I have also experienced this error when accessing CONUS404 data, but used the dataset with the -osn suffix as a workaround. What's going on here? My understanding from the docs is if you're on a USGS computer, it's suggested to use the -onprem data rather than the other sources. And in this particular case, the nhm data is only available 'onprem'.

**Comment by amsnyder** [comment]
The `-onprem` datasets are specifically available on the USGS supercomputers (Denali, Tallgrass, or Hovenweep). Denali and Tallgrass share one filesytem and Hovenweep has its own. You can see from the filepath that the dataset you are interested in is available on **Hovenweep** so you will need to be logged into Hovenweep to access that dataset.

**Comment by putmanannie** [comment]
Thank you -- perhaps update the docs so this is clear to other users? I was reading about it here: https://hytest-org.github.io/hytest/dataset_catalog/README.html and had assumed because I am on Tallgrass, internal to the USGS, that it should be accessible. It's good to know that internal access is only through Hovenweep.

**Comment by amsnyder** [comment]
Yes, I will update those now..we haven't updated them since Hovenweep came online and things are a little more complicated now since it uses its own filesystem.

**Comment by putmanannie** [comment]
Thanks! That's a great idea and would be very helpful.
