### ISSUE TITLE
create repos for CONUS404 processing workflows

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#547]
Move all CONUS404 processing workflows from [here](https://github.com/hytest-org/hytest/tree/main/dataset_preprocessing/archive) into their own repos. We should end with one repo for each of the following:
- conus404_metadata
- conus404_raw - conversion of 2D/3D files to zarr store
- conus404_bias-adjusted - creation of CONUS404 BA zarr store from CONUS404 BA netcdfs available in data release

We will also need a new repo set up for the CONUS404 PGW processing to zarr, which is currently contained in #507

**Comment by pnorton-usgs** [comment]
The following repos have been created and initial commits are completed:

[conus404-metadata](https://github.com/hytest-org/conus404-metadata)
[conus404-raw](https://github.com/hytest-org/conus404-raw)
[conus404-ba](https://github.com/hytest-org/conus404-ba)
[conus404-pgw](https://github.com/hytest-org/conus404-pgw)  (closes #507)

**Comment by amsnyder** [comment]
removed from hytest repo in #556
