### ISSUE TITLE
Model evaluation migration

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#55]
Migrating the data from [model eval](https://github.com/USGS-python/hytest-evaluation-workflows/tree/main/gallery/streamflow), and I have a few questions to resolve in this thread:
1. Are notebooks 1, 2, and 3 being replaced by notebooks the @alaws-USGS and @gzt5142 are working on? Or is it worthwhile to transfer these?
2. Do we need to keep any of these:
  a. [analyzed_data.csv](https://github.com/USGS-python/hytest-evaluation-workflows/blob/main/gallery/streamflow/analyzed_data.csv)
  b. [draft_03_nwm_benchmark_visualization.ipynb](https://github.com/USGS-python/hytest-evaluation-workflows/blob/main/gallery/streamflow/draft_03_nwm_benchmark_visualization.ipynb)
  c. [draft_04_nwm_nhm_benchmark_visualization.ipynb](https://github.com/USGS-python/hytest-evaluation-workflows/blob/main/gallery/streamflow/draft_04_nwm_nhm_benchmark_visualization.ipynb)
3. Are you ok with putting the [preprocessing notebook](https://github.com/USGS-python/hytest-evaluation-workflows/blob/main/gallery/streamflow/01_nwm_benchmark_preprocessing.ipynb) in our `dataset_preprocessing/archive` folder? And then the `model_evaluation` folder will just contain notebooks with evaluation/visualization of those results?

**Comment by gzt5142** [comment]
I had been working through `02_nwm_benchmark_analysis.ipynb` ... and got side-tracked in the rabbit-hole of writing helpers for the math/stats. 

The replacement(s) are in `https://github.com/USGS-python/hytest_notebook_tutorials/tree/dev/Syllabus/L3/NWM%20Benchmark`

Note that those rely on having the math bits defined externally.  Last time we talked about it, opinions were mixed as to whether that's a good idea... Should that conversation continue?

**Comment by amsnyder** [comment]
Maybe I can move over the notebooks for now, with the assumption that your work will overwrite them in the future. I will put notebooks 2/3 in `tutorials`, knowing that we plan to replace them both with full-fledged tutorials at some point.

**Comment by amsnyder** [comment]
We can copy over what you have so far in a new branch - overwriting the current file with your version. Then once it is complete, we can make the merge request?

**Comment by alaws-USGS** [comment]
I think that works. With regards to the NWM workbooks, those were more fleshed out than the CONUS404 notebooks but they will be updated/adapted to turn them into ```tutorials``` rather than ```demos```.

**Comment by sfoks** [comment]
We can delete, that was me just messing around trying to improve the next version before Gene and Andrew came to save us. 
b. [draft_03_nwm_benchmark_visualization.ipynb](https://github.com/USGS-python/hytest-evaluation-workflows/blob/main/gallery/streamflow/draft_03_nwm_benchmark_visualization.ipynb)
c. [draft_04_nwm_nhm_benchmark_visualization.ipynb](https://github.com/USGS-python/hytest-evaluation-workflows/blob/main/gallery/streamflow/draft_04_nwm_nhm_benchmark_visualization.ipynb)

I'm not sure what anaylzed_data.csv is, based on the comit comment, I think this has been resolved and moved into the existing notebooks.

**Comment by amsnyder** [comment]
I think notebook 1 will now live in `dataset_preprocessing`
