### ISSUE TITLE
Combine HPC access instructions from Rich and Andrew/Gene

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#7]
We currently have duplicate instructions to start up a notebook in your working environment:
- https://github.com/USGS-python/hytest-development/blob/main/getting_started.md
- [hytest_notebook_tutorials/README.md at dev · USGS-python/hytest_notebook_tutorials (github.com)](https://github.com/USGS-python/hytest_notebook_tutorials/tree/dev/HPC)

As well as some helper functions to set up the environment:
- [hytest_notebook_tutorials/HPC at dev · USGS-python/hytest_notebook_tutorials (github.com)](https://github.com/USGS-python/hytest_notebook_tutorials/tree/dev/HPC)

These all need to be merged into one set of instructions that we can point to.

**Comment by gzt5142** [comment]
The stuff I wrote for that HPC folder in hytest_notebook_tutorials was based largely on rich's instructions... just trying to automate much of the details and shorten the path as much as possible. 

All that said... if we can work out one tiny technical detail, the best (IMO) solution is the `jupyter-forward` method. It takes away a lot of the tedious set-up on the HPC and runs pretty slick from the user's windows box.  Give or take that one detail.... once I get onprem, I can test and iron out details.

**Comment by amsnyder** [comment]
A few questions about the more automated versions:
- Is there any learning that could come out of the more manual method that we are losing by automating the process?
- How stable do you think the code to automate setup will be? I want to make sure we aren't building a tool for users without a maintenance plan, if it's possible for them to set up without our automated code.

**Comment by gzt5142** [comment]
right.... the automation that I made will handle the one-time operations... So it manages tasks that the user won't ever get practice at or need to do ever again.  In terms of user learning -- the steps I am hiding/automating might be interesting to the technology-minded, but most of it is tedious syntax that I imagine few people will miss if it went away. 

In terms of stability.... good point.  If the HPC environment or login sequence changes, then some not-automated fixes might need to be applied. I'll need to give that a little thought. 

That said -- the best (IMO) option is the `jupyter-forward` system...  It operates from the user's PC as the locus of control, instead of the other way around (logging on to the HPC to do things). I need to test to see if it really will do everything we want. If it does, then I imagine there is even less code maintenance to worry about.  It might require changes to workflow (e.g. "add this option to the command you already run") if the HPC changes... but likely not to code that we maintain.

**Comment by amsnyder** [comment]
@gzt5142 - could you take the lead on coming up with one set of instructions for set up? And maybe check in with @rsignell-usgs to make sure it looks good too? Then open a pull request with the instructions in a folder called `environment_set_up` and tag Rich and I as reviewers?

**Comment by alaws-USGS** [comment]
@gzt5142, I can help with testing if need be but it seems like you and @rsignell-usgs have the best bead on this particular task. Lmk how I can support you.

**Comment by gzt5142** [comment]
Related issue... the conda environment.... I have been working with the attached as my environment definition
```
name: hytest
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - jupyter
  - jupyterlab
  - nbstripout
  - jupyter-server-proxy
  - ipyleaflet
  - ca-certificates
  - certifi
  - openssl
  - xarray
  - intake-xarray
  - rioxarray
  - dask
  - dask-jobqueue
  - dask-labextension
  - graphviz
  - ipycytoscape
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - hvplot
  - diff-match-patch
  - spatialpandas
  - pygeos
  - fiona
  - geoviews
  - datashader
  - zarr
  - numcodecs
  - xesmf
  - statsmodels
  - widgetsnbextension
  - s3fs
```

That was assembled by looking at a few different env definitions I have encountered across the hytest repos (and the pangeo env on esip-qhub).  Any additions or corrections to this?  Can we adopt it (after amendments) as the official minimum standard?

**Comment by rsignell-usgs** [comment]
My impressions:
* we shouldn't need the `defaults` channel, just `conda-forge`
* I was not aware we needed `ipyleaflet, spatialpandas, pygeos, ipycytoscape, seaborn, scikit-learn, scikit-image, ipycytoscape`
* I think we should include `rechunker`, `xbitinfo`, `geopandas` and `gdptools`

**Comment by gzt5142** [comment]
- [ ] I think the `ipleaflet` is a leftover from a failed experiment. Delete. 
- [ ] `ipycytoscape`, `seaborn`, and the `scikit` pieces were related to visualizations... does holoviz depend on them?. I can't remember now why I added them in. Will delete. 
- [ ] Agree to your suggestions for additions... 

I will correct a `.yml` per your advice and add it to the `environment_set_up` folder.

**Comment by rsignell-usgs** [comment]
@gzt5142 sounds good - thanks!

**Comment by gzt5142** [comment]
> I will correct a `.yml` per your advice and add it to the `environment_set_up` folder.

Side question to the side-issue -- do we want to duplicate the functionality of this conda environment `.yml` to a `requirements.txt` for `pip` ?  Seems like all the docs I've seen related to pangeo workflows prefer conda to pip, so maybe it isn't necessary to accomodate pip users.  In terms of cost/benefit, maybe not worth it?

**Comment by rsignell-usgs** [comment]
I think just provide the `environment.yml` file -- we don't want to encourage pip, as the environments will be much more fraught with problems.    Using the conda-forge channel exclusively is our only defense against package incompatibility issues!   

When we encounter packages we need that are on pip but not on conda-forge, we can use [grayskull](https://github.com/conda-incubator/grayskull) to automatically generate the conda recipe, and the conda-forge maintainers appreciate knowing the recipe was generated correctly!

**Comment by alaws-USGS** [comment]
@rsignell-usgs that is really cool!

**Comment by amsnyder** [comment]
FYI - I'm going to pull over Rich's HPC instructions to this repo as a starting point. We have links in other places that point to those instructions on the old repo, and I would like to update all the links to point here. We can modify those instructions later if any changes need to be made coming out of this issue thread.

**Comment by gzt5142** [comment]
Turns out that we do need `seaborn`.   The D-Score visualizations include it.

**Comment by rsignell-usgs** [comment]
Could they use holoviz instead?

**Comment by gzt5142** [comment]
> Could they use holoviz instead (I'm not suggesting we need to switch to holoviz, but just wondering if we _could_)

Done... refactored with examples in hv and matplotlib. See PR #68
