### ISSUE TITLE
Add NHM to catalog

### ISSUE THREAD

**Issue by thodson-usgs** [hytest-org/hytest#70]
> Related to scorecards for dscore... the example notebook has data for NWM and NHM. I'm not seeing the NHM dataset in the intake catalog to source from AWS/S3.

@sfoks @amsnyder We want NHM on aws, right?

_Originally posted by @thodson-usgs in https://github.com/hytest-org/hytest/issues/68#issuecomment-1255227387_

**Comment by amsnyder** [comment]
Closing because this is covered by issue #71 (which existed just as a task, but is now an issue)
