### ISSUE TITLE
NHM data processing and addition to intake catalog

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/hytest#71]
The original NHM data is on [ScienceBase](https://www.sciencebase.gov/catalog/item/5d826f6ae4b0c4f70d05913f), but it probably needs to be reformatted. Parker has a version on Caldera and on S3. @pnorton-usgs and Jacob will work with Rich to reformat this data.

**Comment by amsnyder** [comment]
@pnorton-usgs - I know you've been working on updating CONUS404. Has the NHM data rechunking had any progress, or will it be worked on anytime in the near future?

**Comment by pnorton-usgs** [comment]
@amsnyder I have this on my list of things to do but currently I don't expect to get to it before mid-October at the earliest.

**Comment by sfoks** [comment]
@amsnyder @rsignell-usgs @pnorton-usgs 

The National Water Census has an S3 bucket that they will serve NHM-PRMS v1.0 and v1.1 on in native format and aggregated to HUC12s. Maybe we can tap into that, I chatted Shirley and she will get back to me with the s3 URLs.

**Comment by rviger-usgs** [comment]
@sfoks any update on the NHM results from NWC? Would this version be the same as what your benchmark results are based upon? Is this version what should be used in HyTEST evaluation notebooks?

This is an interesting case, in that WMA potentially has a lot of projects storing redundant copies of the same (or darn similar) data, with no real tracking of this. Don't know if the type of tracking we're doing around CONUS404 (which is largely internal to our own project) would scale to a WMA-wide effort.

**Comment by sfoks** [comment]
@rviger-usgs No updates on this (need to follow-up with Shirley). Last correspondence was that the NWC was thinking of modeling application delivery via globus endpoint. I think there was a meeting today @alamotte-usgs and NHGF with NWC about data and storage. Any mention of modeling application locations and storage on s3 or BlackPearl?

**Comment by alamotte-usgs** [comment]
@sfoks Still digesting today's meeting, I don't think we got that deep into the weeds, but I could be wrong. I will follow up Monday before the Monday NWC call.

**Comment by rviger-usgs** [comment]
fwiw, if we all want to use the same version of the data, I'd love to have a particular project kind of "own" the dataset, serving it, and making this known to the community (e.g., through NHGF catalog). I'd been assuming that would be HyTEST but am flexible (MDMF? NHGF? NWCensus?).

**Comment by alamotte-usgs** [comment]
@rviger-usgs I'd say STAC through NHGF catalog! ~wasn't that the original thinking?

**Comment by amsnyder** [comment]
@sfoks I attended the meeting too, and we did not determine a storage location, but I think Shirley & co. are going to follow up with me because I told them I wanted to discuss the datasets they were serving, storage location, and format to make sure we weren't duplicating efforts. I agree @alamotte-usgs - I think it should be exposed through the NHGF Catalog and STAC if we can. I was hoping to check if @rviger-usgs  would be ok with storing it on the OSN pod if they want to - seems like a really good use case for it.

**Comment by rviger-usgs** [comment]
I'm okay with it being on the OSN pod--think it'd want to be a published dataset to do it that way (don't think this is really a new requirement; NWCensus would probably need this, too). Might need to work with Jacob as the product owner for the PRMS and WRF-Hydro modeling applications. Thinking he'd get it pub'd via Sciencebase and we could replicate in a more usable form (if Sciencebase doesn't have the interfaces or performance that we/Shirley need).

**Comment by pnorton-usgs** [comment]
I have finished kerchunking both NHM v1.0 and v1.1 model output variables for each calibration on caldera. I'm thinking the on-prem kerchunked datasets should be copied to hytest_scratch; @amsnyder what do you think? I've posted a similar question in issue #124. I can also push these to S3, I just need to know where they should go.

**Comment by amsnyder** [comment]
I talked to @pnorton-usgs this morning and suggested he place a copy of these NHM datasets hytest_scratch area for now. If someone needs to work with these in the cloud, we can discuss making an additional copy, but I think we should avoid making extra copies of data that we need to maintain and paying cloud storage fees without a use case. @pnorton-usgs will let us know when he has shared the data and added it to our intake catalog.

**Comment by rsignell-usgs** [comment]
How big are these?  Can they fit in our OSN 100TB allocation?

**Comment by amsnyder** [comment]
Parker gave me some very rough estimates of # of files and size and I think it's somewhere between 50-200 GB of data (big range of uncertainty, I know). We could put them on the OSN pod, but we will just have to move them once we get our actual pod, so I'd rather not put them there unless someone needs them in the cloud.

I am also worried about creating multiple copies of datasets without better dependency tracking to make sure that any dataset updates are propagated to all copies of the data.

**Comment by pnorton-usgs** [comment]
We can close this again but I wanted to provide an update on the total space for the NHM model output. @amsnyder @rsignell-usgs The total size is about 800G.
