### ISSUE TITLE
Develop main/front-facing/intro README.md 

### ISSUE THREAD

**Issue by sfoks** [hytest-org/hytest#8]
Develop a get started README.md to discuss folder structure and contents, where to get started.

draft::

HyTEST-ORG
"The Hydro-Terrestrial Earth System Testbed Organization (HyTEST-ORG) is an open-source, community-based group that seeks to improve hydrologic and terrestrial modeling capacity. We seek collaboration with the community of earth, atmospheric, and data scientists to aid in this goal. We hope to provide helpful tutorials and examples of working and evaluating performance of large-scale hydrologic and terrestrial models."

**Comment by gzt5142** [comment]
Closing... covered by #119  (and others)
