### ISSUE TITLE
CONUS404 zonal statistics

### ISSUE THREAD

**Issue by alaws-USGS** [hytest-org/hytest#85]
Create second data preparation notebook and start with computing zonal statistics at HUC6 basin-level in the Delaware River Basin.

**Comment by rsignell-usgs** [comment]
@alaws-USGS  for zonal stats in Python we've been using the [gdptools](https://code.usgs.gov/wma/nhgf/toolsteam/gdptools) package that USGS-WMA (Rich McDonald @rcmd-mscb) built.    It uses exact polygon geometry to calculate the weights, the time consuming step, then these weights can be used for the many time steps we often have.    This is what distinguishes gdptools from the many other zonal stats packages in python. 

Here's an example of using it for CONUS404 in the Delaware River Basin:

https://nbviewer.org/gist/a17da361a9e23108be723adafb7b9eba

 I took a quick look at https://github.com/hytest-org/hytest/blob/arl-85-conus404-zonal/dataset_preprocessing/tutorials/CONUS404/conus404_zonal_point_statistics.ipynb and it seems like you are not using the gdptools library, right?
