### ISSUE TITLE
Compare zonal statistics methods for CONUS404

### ISSUE THREAD

**Issue by alaws-USGS** [hytest-org/hytest#89]
Comparing three methodologies for computing zonal statistics:
1. `rioxarray` and `geocube` 
2. [conservative region aggregation](https://discourse.pangeo.io/t/conservative-region-aggregation-with-xarray-geopandas-and-sparse/2715)
3. `gdptools` workflow

Checking each for time to completion, complexity of code generation, and accuracy of outputs.

Builds on conversations from #10

**Comment by rsignell-usgs** [comment]
@alaws-USGS , as I understand it, a current blocker for running the Abernathy approach to calculate zonal stats is that it expects to find `cell_bounds`, right?     @pnorton-usgs , yet another thing we should add to the CONUS404 datasets to make them more CF-compliant (and functional with tools like this that expect to find them).    Luckily, this should be super easy since we have a uniform 4 km grid!

**Comment by pnorton-usgs** [comment]
That would be good to have. I'll add it to my list of things to do.

**Comment by rsignell-usgs** [comment]
@alaws-USGS , should this be closed?   You are still getting NaN with the rabernathy method, right?

**Comment by sfoks** [comment]
Reopened, I think here would be fine to document progress on the Abernathy/conservative region agg

**Comment by alaws-USGS** [comment]
@rsignell-usgs and @sfoks, this is a good place. I had originally closed it as I was taking a pause on working on this.

**Comment by rsignell-usgs** [comment]
Okay, my plan is to:
* [x] successfully run the [Abernathy convervative regridding original notebook](https://notebooksharing.space/view/c6c1f3a7d0c260724115eaa2bf78f3738b275f7f633c1558639e7bbd75b31456#displayOptions=) from this [Pangeo Discourse post]](https://discourse.pangeo.io/t/conservative-region-aggregation-with-xarray-geopandas-and-sparse/2715) on ESIP qhub
* [ ]  swap out original country boundaries and swap in HUC from hyriver
* [ ] swap out precip from NASA / NOAA Global Precipitation Climatology Project and swap in CONUS404 precip

**Comment by alaws-USGS** [comment]
Based upon conversation during the weekly call on 11/14/22, it was decided that until `gdptools` has matured in reference material, aggregation methods, and data format options (in memory and on disk), the conservative regridding method put forward by Ryan Abernathy will be used for zonal statistics (*Note*: Rich McDonald had said that he would be adopting Ryan's method within future iterations of `gdptools`).

Much of this is based up my experience working with all three methods and additional work by @rsignell-usgs, including his accomplishments with coding both methods: [conservative regridding](https://jupyter.qhub.esipfed.org/hub/user-redirect/lab/tree/shared/users/rsignell/notebooks/regridding/conus404_regrid_huc12.ipynb) and [gdptools](https://jupyter.qhub.esipfed.org/hub/user-redirect/lab/tree/shared/users/rsignell/notebooks/regridding/conus404_regrid_huc12_large_instance_rmcd_RMA.ipynb)
