### ISSUE TITLE
Sync CONUS404 cloud and onprem datasets

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#9]
@sfoks and I discovered yesterday that the CONUS404 hourly 40 year dataset on the cloud did not have projected coordinates.   Subsequent chat with @pnorton-usgs revealed that on-prem version DOES have projected coordinates.    

We need to sync these datasets so they are consistent.    
@pnorton-usgs can you please sync these using AWS CLI or Globus, which should push the new content to the cloud version.

**Comment by rsignell-usgs** [comment]
I guess instead of syncing you could just copy over:
* `.zmetadata`
* `./east-west/*`
* `./north-south/*`

**Comment by rsignell-usgs** [comment]
@pnorton-usgs , I believe you told me that the new hourly dataset is available on-prem and has been moved to cloud, ready for @amsnyder to move from s3://nhgf-development/workspace/ to s3://nhgf-development, correct? 

Where is it though?
https://nbviewer.org/gist/d32a076a04e50caf83cd68bb0e8b0359

**Comment by pnorton-usgs** [comment]
The workspace copy is available on at `s3://nhgf-development/workspace/conus404_hourly_202209.zarr`.

**Comment by amsnyder** [comment]
I will work on moving that over to `s3://nhgf-development/conus404/conus404_hourly_202209.zarr` right now!

**Comment by amsnyder** [comment]
There's a "folder" in here named just `/` that has data inside of it that I would expect to see inside a variable. Do you think one of the variables didn't get copied over correctly? Or is this expected?

**Comment by amsnyder** [comment]
inside the folder named `/`:
![image](https://user-images.githubusercontent.com/30877272/192041840-066583d1-9454-4771-b9de-8f0a278fb9f0.png)

**Comment by pnorton-usgs** [comment]
That directory is from an earlier script error; it can be removed.

**Comment by amsnyder** [comment]
The hourly data has all been transferred to `s3://nhgf-development/workspace/conus404_hourly_202209.zarr`. Does @rsignell-usgs or anyone else want to test it out and see if it looks good?

**Comment by alaws-USGS** [comment]
@amsnyder thanks for doing this! Has this been added to the intake catalog?

**Comment by rsignell-usgs** [comment]
I just submitted a PR to update the on-prem hourly/daily/monthly and the cloud hourly: https://github.com/hytest-org/hytest/pull/80

**Comment by amsnyder** [comment]
I am transferring the hourly updates directly into `s3://nhgf-development/conus404/conus404_hourly_202209.zarr/`

I am also starting the transfer of the daily and monthly data from:
`s3://nhgf-development/workspace/conus404_daily_20221003.zarr/`
and
`s3://nhgf-development/workspace/conus404_monthly_20221003.zarr/`

into:
`s3://nhgf-development/conus404/conus404_daily_202210.zarr/`
and
`s3://nhgf-development/conus404/conus404_monthly_202210.zarr/`

**Comment by amsnyder** [comment]
daily and monthly data, as well as the hourly updates have been moved from the `workspace` dir to the `conus404` dir. @pnorton-usgs are there any other planned updates to the dataset that you expect coming down the line? (aside from discussions about bias-corrections to the data)

**Comment by amsnyder** [comment]
And @pnorton-usgs can you confirm that I should delete the following variables from the dataset, now that the hourly updates have been synced?
I_ACLWDNB Bucket for downwelling longwave radiation flux at bottom
I_ACLWUPB Bucket for upwelling longwave radiation flux at bottom
I_ACSWDNB Bucket for downwelling shortwave radiation flux at bottom
I_ACSWDNT Bucket for downwelling shortwave radiation flux at top
I_ACSWUPB Bucket for upwelling shortwave radiation flux at bottom

**Comment by amsnyder** [comment]
The variables above have not yet been deleted, but @alaws-USGS can't access them. I'm not sure why.

I believe anyone using those variables, should transition to these new variables that Parker computed:

> The following solar radiation variables have been updated. For these variables the full accumulated value was computed from the AC* and *_AC* variables, replacing the original AC* variables. For each timestep values now represent the accumulation from the model start (1979-10-01). The metadata has been updated to reflect this change.
> 
> ACLWDNB  Accumulated downwelling longwave radiation flux at bottom
> ACLWUPB  Accumulated upwelling longwave radiation flux at bottom
> ACSWDNB  Accumulated downwelling shortwave radiation flux at bottom
> ACSWDNT  Accumulated downwelling shortwave radiation flux at top
> ACSWUPB  Accumulated upwelling shortwave radiation flux at bottom

**Comment by alaws-USGS** [comment]
From a conversation I had with @pnorton-usgs:
![image](https://user-images.githubusercontent.com/108412194/204595118-90fe0b88-14ad-4e21-a94f-73c840230511.png)

**Comment by amsnyder** [comment]
I've deleted the "bucket" radiation variables (starting with I_) from the hourly CONUS404 dataset on S3 because most users will probably want the computed radiation data. @pnorton-usgs has a copy of the "bucket" radiation data on Caldera for backup in case it is needed at any point. Closing this issue as these datasets are all currently in sync.
