### ISSUE TITLE
Using Open Storage Network (OSN) Pod object storage?

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#90]
I mentioned we had 100TB of OSN space allocated to us while we wait for our own OSN pod.   But how do we use it?

**Comment by rsignell-usgs** [comment]
We've been assigned a bucket called s3://rsignellbucket2.    Because an OSN endpoint isn't at AWS, you need to supply the `endpoint-url`, but you don't need credentials to read.    

You do need credentials to write of course.   

I set up my credentials with the aws CLI under a profile called "osn-renci":
``` 
aws configure --profile osn-renci
```
and answering the first two questions with the security pair we were assigned (ask me if you need them)  and answering the last two questions with "us-east-1" and "json".   I think the region is irrelevant for OSN, but it asks for one. 

Here are examples using the AWS CLI
``` 
aws s3 ls s3://rsignellbucket2/testing/  --endpoint-url https://renc.osn.xsede.org/ --no-sign-requestaws s3 cp ortho_2021_10_7_sageLot_noalpha_clip_cog.tif s3://rsignellbucket2/testing/ --profile osn-renci --endpoint-url https://renc.osn.xsede.org/aws s3 sync ./cogs s3://rsignellbucket2/gene/cogs  --profile osn-renci --endpoint-url https://renc.osn.xsede.org
``` 
You can use these same parameters with fsspec, thusly:
``` 
fs_read = fsspec.filesystem('s3', anon=True, skip_instance_cache=True,
                            client_kwargs={'endpoint_url': 'https://renc.osn.xsede.org'})
fs_write = fsspec.filesystem('s3', profile='osn-renci', skip_instance_cache=True, 
client_kwargs={'endpoint_url': 'https://renc.osn.xsede.org'})
```
or if you have the S3 credentials being passed using environment variables:
```fs_write = fsspec.filesystem('s3', anon=False, skip_instance_cache=True, 
client_kwargs={'endpoint_url': 'https://renc.osn.xsede.org'})
```
Does this all make sense?

**Comment by rsignell-usgs** [comment]
@gzt5142 would this help with #12 ?

**Comment by gzt5142** [comment]
I will try it -- I have been having success writing to nhgf-workspace for the purposes of the tutorials.  I will re-run a version writing to this store... 

The kubernetes cluster workers will need the correct profile/credentials to write to this space, which is the only hiccup I can see which might set me back. I believe that I just need to give ebdpy the correct profile/credentials when spinning up. I'll reach out if i run into difficulties.

**Comment by alaws-USGS** [comment]
@rsignell-usgs and @gzt5142, I've been ruminating on a slight shift in how we handle I/O on data for the tutorials and I think OSN would be the right solution. Specifically, the "the tutorial user can access but not write the data" portion. This idea also makes the assumption that all tutorial users (federal employees atm) would not be getting credentials for the OSN storage or there won't be a public key.

The main tutorials focus has been bringing in data, preparing it for analysis, analysis, and visualization. What if we handled output of intermediate datasets (those between preparation and analysis notebooks, etc) by showing ***how*** to perform the action but ***not*** actually perform it. Once we have the final data prepared, we can add it to OSN ourselves and allow users to just perform reads so there is no danger of tutorial users modifying our tutorial data. One downside is this does mean we have to maintain the tutorial data BUT for tutorials this should be pretty lightweight. 

I'd welcome any thoughts on this.

**Comment by rsignell-usgs** [comment]
I like this idea!

**Comment by gzt5142** [comment]
This works very well....  Performance seems to be on par with what I was getting out of the nhgf development workspace. 
 
```
fs_write = fsspec.filesystem('s3', 
        profile='osn-renci', 
        skip_instance_cache=True, 
        client_kwargs={'endpoint_url': 'https://renc.osn.xsede.org'}
        )
outfile = fs_write.get_mapper('s3://rsignellbucket2/testing/gzt5142/nwis_out_gzt5142.zarr'
```
Cluster workers configured as: 
```
import sys
sys.path.append('/shared/users/lib')
import ebdpy as ebd

## These credentials must match those used to open the fs_write 
## filesystem if you want workers to write data
aws_profile = 'osn-renci'
aws_region = 'us-east-1'
endpoint = 'https://renc.osn.xsede.org'
ebd.set_credentials(profile=aws_profile, region=aws_region, endpoint=endpoint)

worker_max = 30
client, cluster = ebd.start_dask_cluster(
    profile=aws_profile,   ## @rsignell-usgs do we need this since we set_credentials() above?
    worker_max=worker_max,
    region=aws_region, 
    use_existing_cluster=True,
    adaptive_scaling=False,
    wait_for_cluster=False,
    worker_profile='Medium Worker',
    propagate_env=True
)
```

I am refactoring the NWM benchmarking tutorials to write to this space instead of nhgf.

**Comment by rsignell-usgs** [comment]
@gzt5142 , when we are are using just the cores on the machine that the notebook is running on (e.g. a single process, using Dask but not Dask Distributed, or using Dask Distributed with a Local Cluster, we can specify the profile to use in fsspec and it will read from the `~/.aws/credentials` file on the local filesystem.

When we use Dask Distributed with Dask Gateway (using Kubernetes), those workers don't see the filesystem so we don't use that method of providing S3 credentials.  

When we use the `ebd.start_dask_cluster()` helper function, we specify a profile, but that profile is turned into environment variables, and then when we specify `propagate_env=True` it propagates the environment vars to the workers. 

When we use the `ebd.set_credentials` command, it reads the specified profile and creates the environment variables, which can be handy when you are not creating a cluster, but have clients that require credentials specified via environment variables. 


Does that make sense?

**Comment by gzt5142** [comment]
I understand the workflow... I even went so far as to `del os.environ["AWS_PROFILE"]` to ensure that it was not available for sneaky and nefarious steps taken without my knowledge or understanding.  

The profile name leaked through via some other mechanism, which I still have not identified... 
My ultimate solution was to set the key environment variables using the code sample you supplied. Something like: 

```python
awsconfig = configparser.ConfigParser()
awsconfig.read(
    os.path.expanduser('~/.aws/credentials') # default location... if yours is elsewhere, change this.
)
os.environ['AWS_ACCESS_KEY_ID'] = awsconfig[_profile_nm_]['aws_access_key_id']
```

This worked.  Full notebook here: 
https://jupyter.qhub.esipfed.org/hub/user-redirect/lab/tree/shared/users/gzt5142/hytest/model_evaluation/tutorials/nwm_streamflow/01_Data_Prep.ipynb

**Comment by rsignell-usgs** [comment]
Phew!    Nice sleuthing!

**Comment by rsignell-usgs** [comment]
Closing this since we have multiple people successfully writing to OSN storage allocation (we are still waiting to buy our pod until testing of the new pod design has been completed, hopefully by end of January, 2023)
