### ISSUE TITLE
[?] Use 'module' on HPC hosts to standardize environment

### ISSUE THREAD

**Issue by gzt5142** [hytest-org/hytest#91]
Have had a few conversations with the HPC admin team about the 'correct' way to set up custom conda environments for groups of users.  Individual conda installs and environments in home directories are good enough for one-off configurations, but for larger projects ('larger' in terms of user count -- and I don't have a number for what counts as large vs small), a standardized common environment is preferred. And it's easier for ARC to support. 

Here's what that would look like from the perspective of the user experience.
We've got a few user experience stories right now (and should probably keep these options):
* OnDemand Web Launch
  * A 'HyTEST' launcher is included at system level on the OnDemand app server. 
* Custom Launcher via shell: 
  * login to denali (or tallgrass)
  * `module load hytest`
  * `jupyter lab --ip=0.0.0.0`
* Using jupyter-forward:
  * Add `module load hytest` to the `.bashrc`
  * Run `jupyter-forward` from desktop  

That's it. No installing conda; no installing a custom environment; no PATH modifications to `.bashrc` (these extra steps are still possible, and some folks may like to do that for one reason or another -- but it would not be required).

If the module is crafted with some care, that `module load hytest` would be safe to put in the `.bashrc` so as to be available automatically. This is key to having the correct environment launched via `jupyter-forward` invocation. (With one adjustment to `jupyter-forward`, the requirement to modify `.bashrc` can be lifted).

-----

In terms of implementation, this (in broad strokes) would be the necessary infrastructure/configuration:

**Centralized location**
- [x] A world-readable project space on /caldera (this already exists in some form)... for the purposes of discussion, let's call `PROJECT_DIR = /caldera/projects/yada/yada/yada/hytest`
- [x] `${PROJECT_DIR}` would hold hytest-specific conda environments, modules, and other 'infrastructure'  I'm told that having the python executable and support libraries on `/caldera` is an advantage (vs on the `/home` file system) when running submitted jobs.
- [x] This would be readable globally (so anybody who wants can use it) but writable only by a hytest user.. this means that hpc admin staff are not involved if upgrades are needed. 

**environments and modules**
- [x] Conda environment(s) in `${PROJECT_DIR}/envs` (or similar) -- We would install the 'correct', 'supported', 'blessed', 'standard' environment, with jupyter components, python libraries, etc that the project requires and is willing to support. This is **The One**&trade; (:neo:, :matrix:).
- [x] `${PROJECT_DIR/modules`  would hold hytest-specific modules.  These are configured such that any user could execute `module load hytest` (or similar) on either Denali or Tallgrass.  This would manipulate the user's environment such that conda, python, jupyter, and anything else we want in `${PROJECT_DIR}` would be plumbed in automatically, and correctly. 
- [x] The `hytest` module would be available to any user on the system.
- [x] A standard hytest module will significantly ease the implementation details of the OnDemand app

**Dependencies**
- [x] Using the `modules` interface means we can enforce dependencies (like force-loading `nano` or some GPU libraries, etc, etc).  Dependencies are managed by `module` so we don't have to invent a system. 
- [x] Platform-specific installations are possible (and transparent) -- if differences exist beteween denali and tallgrass, we can account for them with `module`. 

Lopaka has agreed to help set this up so that the project can have a consistent and easy-to-use environment for hytest users. This will hopefully make hytest usage easier, which means ARC has fewer support calls when things break. If we decide that this system is an advantage, we should **absolutely** document in detail the configuration components so that other HPC centers or outside users can replicate the functionality if they want. 

Questions or comments?  Would love to discuss at our next check-in meeting.

**Comment by rsignell-usgs** [comment]
@gzt5142 , this sounds perfect -- thanks so much for figuring this path out!    This allows us to provide ready-to-go environments for our users on HPC, but gives us the control to modify them without HPC admin help when they need to be modified to meet some new HYTEST use case (these invariably come along sooner than expected). 

What is the next step?

**Comment by gzt5142** [comment]
> What is the next step?

The steps: 
- [ ] Need to get write permission and establish the project space on `/caldera` .  _I am working with Lopaka to do that now._ 
- [ ] Create a standardized conda environment in that project space
- [ ] Define and test the `module`
- [ ] Install `module` for global access
- [ ] Refactor the OnDemand custom jupyter app to use that module.

**Comment by gzt5142** [comment]
> * Need to get write permission and establish the project space on `/caldera` .  _I am working with Lopaka to do that now._

I propose `/caldera/projects/hytest` Any reason not do do that?  

Should it go in `/caldera/projects/usgs/water/hytest` instead?  If this is cross-agency, then perhaps putting it under USGS is problematic.

If no objections, I'll make progress with `/caldera/projects/hytest`.

**Comment by sfoks** [comment]
/caldera/projects/usgs/water/impd/hytest  this directory already exists, and I think there is an 'account' called hytest but I'm not positive about this. @pnorton-usgs @rsignell-usgs might know

**Comment by thodson-usgs** [comment]
Not using these files at the moment. Might want to save
`/caldera/projects/usgs/water/impd/hytest/eval/data/proc/statistical_benchmark` 
but it can be regenerated from the data releases without too much effort.

**Comment by gzt5142** [comment]
OK.... looks like we are going to charge ahead with 
```
/caldera/projects/usgs/water/impd/hytest
```
as the `PROJECT_DIR`.

I'll work with Lopaka from HPC admin team to set up: 

```
${PROJECT_DIR}/envs
${PROJECT_DIR}/modules
${PROJECT_DIR}/ood
```

Once I can prove out the `envs` space, we can think about deprecating the existing `environments`.  I'm reluctant to remove the existing until I have a known-to-work replacement. Depending on Lopaka, I may have this whole thing on line this week.

**Comment by gzt5142** [comment]
Slight evolution, but it seems to be working in initial testing. 

If you want to test, log into `denali`, then execute:
```
module use --append /caldera/projects/usgs/water/impd/hytest/modules
module load hytest
```
You should now have `jupyter` in your path (among other things) and a hytest-specific conda environment is loaded from `/caldera/projects/usgs/water/impd/hytest`

```
jupyter lab --no-browser --ip=0.0.0.0 
```

Then launch the link it gives you (should be something like `http://denali-login2:8888/lab?token=bunchanumbers` )

A few notes: 

- That `module use --append` statement is only needed during this testing period.  Lopaka will install the module in a system-wide location once we're satisfied with it.  
- If you've previously spawned a jupyter server from denali, there may be some config in your `~/.jupyter` and `~/.local/share/` directories that may throw a couple of warnings -- It is useful to know if that happens, so I can plan a better way to account for it. 
- If you already have kernels installed from a previous config, jupyter server will still find them and you can continue to use them.

**Comment by rsignell-usgs** [comment]
@gzt5142 , I logged onto denali and tried this out.   Worked - awesome!
Two things:
* the link didn't have the `?token=bunchanumbers`
* I didn't see any of my environments available (but I see them if I open a terminal in Jupyter and do `conda info -e`

**Comment by gzt5142** [comment]
@rsignell-usgs 

> 1. The link didn't have the `?token=bunchanumbers` (but it worked!)

Right.... I forgot about passwords....

I unwound the jupyter server setup, setting password, etc. to mimic what a new user would experience.   Which is why my server spin-up defaulted to token authentication.  My guess is you have a jupyter server password, which clearly also works. 

I'm still looking at the alternate kernel config -- thanks for that information. When I launch, it does consult kernels found in `~/.local/share/jupyter/kernels` ... and I see that it found your Julia kernel.   but I agree that it would be useful to find kernels for all those conda envs listed in `~/.conda/environments.txt` ... I will look at how best to do that.

**Comment by gzt5142** [comment]
OK.... so I put [nb_conda_kernels](https://anaconda.org/conda-forge/nb_conda_kernels) into the central hytest conda environment.  The jupyter server spawned from there *should* find other conda environments. 

The question I have yet to test is whether it will find all environemnts, even if they don't share the  same root (in `/caldera`).  

If you spin up jupyter server now, it should at least try to find other environments. 

If that doesn't do it, then we have to register each environment as its own kernel.  Tedious, but will definitely work.  Can be automated. 

--gt

**Comment by rsignell-usgs** [comment]
@gzt5142 I just realized that we shouldn't be running things on the master node, and so I requested an interactive node using: 
``` 
#!/bin/bash
salloc -A woodshole -t 04:00:00 -N 1 srun --pty bash
```
and then used your commands above:
``` 
module use --append /caldera/projects/usgs/water/impd/hytest/modules
module load hytest
jupyter lab --no-browser --ip=0.0.0.0 
```
this spits out a message:
``` 
Jupyter Server 1.18.1 is running at:
[I 2022-10-28 13:13:10.779 ServerApp] http://nid00639:8888/lab
```
but of course that doesn't work.

**Comment by gzt5142** [comment]
OK... this is a problem. . . . 

Jupyter uses the output of `hostname -f` to set its 'fully qualified domain name' . . In most configurations, that name will resolve via DNS.  For compute nodes, this is not the actual fully qualified domain name. -- and that node name (`nid000639`) is not in the DNS.  This is the problem. 

And so.... I don't think it likely that we will convince ARC to put nodenames in the DNS.  So the challenge is how to override jupyter's sensible default of the FQDN so that it uses the IP or some other address in the DNS.  Other plan is to use port forwarding. 

In the long term, I'm hoping that this system won't be needed to launch jupyter servers.... with a correctly curated environment and jupyter server config, the server can be spun up via OnDemand. That's the direct that I am hoping to move toward -- but it should also be possible to do what you just did.... for the user who wants a custom conda environment, or needs for some reason to use denali instead of tallgrass. 

So now... my to-do list includes: 

- [ ] Including custom conda environments
- [ ] Works in a non-interactive allocation on denali
- [ ] test the impact of password vs token authentication

**Comment by pnorton-usgs** [comment]
For my work in Jupyter on denali I routinely use port forwarding and it works well. Let me know if you would like to see the batch file I use.

**Comment by gzt5142** [comment]
>
> For my work in Jupyter on denali I routinely use port forwarding and it works well. Let me know if you would like to see the batch file I use.

I have an example around here somewhere.... but I would also like to see what you are using. 

Thanks,

**Comment by thodson-usgs** [comment]
I do too, but I'd also like to see how @pnorton-usgs does it. 
Would it be possible to post a "public" version here?

From memory, I had a nice script working on denali, but it wouldn't work on tallgrass. Something to do with the name returned by `hostname` was actually resolvable over the network.

**Comment by rsignell-usgs** [comment]
@gzt5142 , can we use the module approach with jupyter forward?

**Comment by gzt5142** [comment]
> @gzt5142 , can we use the module approach with jupyter-forward?

Yes... with one caveat.  jupyter-forward expects to find jupyter (via `which jupyter` run via `ssh`) **before** it executes any custom commands you enter on the `jupyter-forward` command).  The end result of that is that you should put `module load hytest` in the `.bashrc`.   

I was really hoping to remove this one hurdle for use with `jupyter-forward` -- and there may be a way I have not found yet -- but that's what I understand so far.

**Comment by gzt5142** [comment]
Thanks for sharing -- I'll give a test this afternoon.  That script looks like it is based on the "standard" (if there is such a thing) example jupyter_start.sh from Pangeo.

**Comment by gzt5142** [comment]
So it seems we have a few options for users... each of these things works: 

1) Use OOD app to run jupyter notebooks on a tallgrass allocation
2) `module load` the hytest environment as a way to launch a personal server much like @pnorton-usgs does. 
3) use `jupyter-forward` from the PC in conjunction with `module load` on the HPC host. 

And also more complicated versions of 2 and 3 are possible (in which users create their own custom conda envs). . . . So I suppose the question now is, what do we want to recommend for users?  Which of these do we want to document and recommend?

**Comment by gzt5142** [comment]
@thodson-usgs wrote:
> From memory, I had a nice script working on denali, but it wouldn't work on tallgrass. Something to do with the name returned by `hostname` wasn't resolvable over the network

This might be the FQDN issue again.  Just a guess.... Jupyter uses output from `hostname -f` to establish the network name of the host on which it runs.  the Fully Qualified Domain Name is assumed to be just that -- a resolvable DNS domain name.  But that doesn't seem to be the case for these nodes within the HPC. That's just a quirk of how the ARC folk have configured the hosts.  You might be able to force the "_hostname_" by using the IP address itself. Use `ifconfig` to get that (an ugly hack, but it can work (in theory; never tried it myself)).

**Comment by gzt5142** [comment]
I have submitted a request to Lopaka to make the `module` available to other users without their needing to adjust their `.bashrc`

Similarly, I have asked to have the customized tallgrass jupyter server app available outside of my development sandbox.  

More details as they become available.
