### ISSUE TITLE
Set bokeh < 3 on all environment.yml files

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#92]
As heard from @jbednar on the [Pangeo weekly meeting](https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU/edit) last week, it would be good to be proactive and set `bokeh<3` in our environments, as when it is actually released, it is almost guaranteed to break some functionality in holoviz.    Then when holoviz folks finish working through the issues, we can unpin it. 

I've set this on the `users/pangeo` enviroment on ESIP qhub, but @gzt5142 noted we need to do this for any HPC and local hytest environments as well.

**Comment by jbednar** [comment]
Note that current panel versions pin bokeh less than 3, so if you pin to a current Panel version, as would be good practice anyway, you won't *also* need to pin bokeh.

**Comment by gzt5142** [comment]
our current environment.yml file does not specify panel or bokeh... just hvplot
https://github.com/hytest-org/hytest/blob/main/environment_set_up/HyTEST.yml

I will add a line to set
```text
  - panel=0.14.* 
```
