### ISSUE TITLE
New mem management in Dask for rechunking and other problematic workflows

### ISSUE THREAD

**Issue by rsignell-usgs** [hytest-org/hytest#93]
Also as heard on the [Pangeo weekly meeting](https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU/edit) last week:  since September 30 (>=2022.9.2), Dask has a new feature that can dramatically lower memory in many situations, and the reading-too-much-data-before-writing problem was specifically mentioned as being fixed by this:  https://github.com/dask/distributed/discussions/7128

@pnorton-usgs and I have hit this a lot when doing rechunking workflows, and have resorted to things like only processing some fraction of the time steps at a time, like 6 months of data at at time for a 40 year workflow.   Hopefully this will help! 

@pnorton-usgs , @amsnyder, @kathymd

**Comment by gzt5142** [comment]
I started looking at this on esip -- the pangeo environment there uses dask `distributed` version 2022.4.2; with this option available only after 2022.9.2. 

I tried to create my own environment (using form at https://jupyter.qhub.esipfed.org/conda-store/create/ )... But it is telling me that my request is not authorized.   I feel like I'm missing an important step. Do you have any guidance to help steer me toward upgrading `distributed` to include this feature?

**Comment by gzt5142** [comment]
> I feel like I'm missing an important step.

Yep... a very important step... turns out that your new browser window needs to explicitly login again, rather than relying on the cookie/token.  I'm all better now.  Sorry for the noise.

**Comment by gzt5142** [comment]
FYI... the sample codeblock for gateway/pangeo does not work as published. The specific call to set environment variables does not work in the esip/qhub environment.  This does: 

```python
import os
os.environ['DASK_DISTRIBUTED__SCHEDULER__WORKER_SATURATION'] = "1.0"
# set other environment vars as needed (AWS-specific, for example)

from dask_gateway import Gateway
gateway = Gateway()
options = gateway.cluster_options()
options.environment_vars = dict(os.environ)
cluster = gateway.new_cluster(options)
```

--gt

**Comment by gzt5142** [comment]
I added this line:
```
os.environ['DASK_DISTRIBUTED__SCHEDULER__WORKER_SATURATION'] = "1.0"
```
to the start-dask helper. 

closing
