### ISSUE TITLE
Status of hytest-development

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#99]
@amsnyder Should we be continuing to use https://github.com/USGS-python/hytest-development for the development of various processing workflows or should it be moved under hytest-org (under some subdirectory I'm assuming)?

**Comment by amsnyder** [comment]
They should go in here now: https://github.com/hytest-org/hytest/tree/dev/dataset_preprocessing/archive

We won't be putting anything on USGS-python moving forward.
